### ISSUE TITLE
the new 3.6.0 version does not contain the  #959 fixes 

### ISSUE THREAD

**Issue by miyou995** [django-tenants/django-tenants#1001]
on the master branch of the github repo the code is updated and contain the #959 PR fixes but when you install the 3.6.0 from pypi or download the ziped file from Source Distribution on the pypi the fixes are not there and it throu the old erorrs mentionned here 
https://github.com/django-tenants/django-tenants/pull/959
and the image bellow show the difference on line 158
![sgtd](https://github.com/django-tenants/django-tenants/assets/48582036/42e3a912-088a-45cd-8b33-9dd6b627a9ee)

**Comment by tomturner** [comment]
Should be sorted now with 3.6.1
