### ISSUE TITLE
Microsoft SQL server Support

### ISSUE THREAD

**Issue by belltagy** [django-tenants/django-tenants#1007]
I hope this message finds you well. I'm reaching out because I'm interested in contributing to This project  by adding support for Microsoft SQL Server. Before I start working on this, I wanted to seek your guidance on the specific areas of the codebase that might need modification.

Here are a few questions I have:

- Could you please point me to the relevant parts of the codebase where database backends are handled?
- Are there specific modules or files that deal with database-specific functionality that I should be aware of?
- Are there any existing conventions or patterns in the project that I should follow when introducing support for a new database backend?
- I'm committed to ensuring that the implementation aligns with the overall structure of the project, and I'd greatly appreciate your insights into where I should focus my efforts.

Thank you for your time and for maintaining such a valuable project. I'm looking forward to contributing and appreciate any guidance you can provide.

B,R

**Comment by tomturner** [comment]
Banch the project if you want this. I have no interest.
