### ISSUE TITLE
Django 5.1 Compatibility

### ISSUE THREAD

**Issue by JojoBonnie** [django-tenants/django-tenants#1074]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. django-tenants 3.6.1 requires Django<5.1,>=2.1, but you have django 5.1 which is incompatible. 

Is anyone working on this update? If not, how can I contribute?

**Comment by cclauss** [comment]
This downgrading behavior was discussed and fixed in #1061 but a new release to PyPI is ___required___ .
* #1061

**Comment by miyou995** [comment]
@tomturner when should we expect a new PyPi release ?

**Comment by cclauss** [comment]
This can be closed... https://pypi.org/project/django-tenants
