### ISSUE TITLE
Deployment 300 schemas

### ISSUE THREAD

**Issue by begyy** [django-tenants/django-tenants#1082]
Problem
I have around 300 schemas in my database, and every deployment takes over 15minutes. The more clients I have, the longer the deployment time becomes. However, during each deployment, no migrations are run, and I'm not sure if migrations have been applied to all schemas.

When I try to check if the migrations have been applied by using the command:
manage.py showmigrations --list

it only shows the default public schema. This means I can't easily verify if migrations have been applied to all schemas.

Solution
To solve this issue, I need to set an ordering for the migration of schemas so that the public schema is processed last. For example, the order could be:

other1_schema
other2_schema
other3_schema 
...
other500_schema
public

This way, when I use the command:

manage.py showmigrations --list
I can accurately determine if migrations have been applied to all schemas because the public schema will appear last.

I'm considering implementing this solution by allowing an option to specify the ordering for the migration schemas, such as:

migration_schemas --ordering=public,other_schemas
This approach should resolve the issue and make the deployment process more efficient.

**Comment by mikicz** [comment]
Have you ever come to a solution for this? I would be interested in making our migrations faster

**Comment by hanckmann** [comment]
Hi,
I am facing a similar issue. I am hosting my application on Heroku. If the startup time of an app (Django docker container) takes more than 2 minutes, the dyno fails. I am running into this currently.
Can you/anyone give me any pointers on this?

**Comment by begyy** [comment]
@hanckmann @mikicz Hi,
https://django-tenants.readthedocs.io/en/latest/use.html#migrate-schemas-in-parallel
