### ISSUE TITLE
Copy database to make fast tenant testcase even faster

### ISSUE THREAD

**Issue by tomturner** [django-tenants/django-tenants#132]
I have a lot of added value in my database which takes a long time to insert. I need a way of creating the test database very fast. The idea is to copy the database the first time the database has been created. I know that copied database will get out of date because of migrations however all one need to do if drop that database.

**Comment by MiltonLn** [comment]
Do you have an example of how many tests you have and how many time they take to run with FastTenantTestCase?

**Comment by tomturner** [comment]
I have about 15 test however it takes too long in writing them because it takes 90 secs to create my blank database hence this update

**Comment by tomturner** [comment]
There a slight problem with it at the moment

**Comment by MiltonLn** [comment]
Your actual problem is that you need to load a lot of initial data (Say cities, countries, etc) to your database before running the tests? because in my case with FastTenantTestCase is enough. This can be faster but with the current speed is enough

**Comment by tomturner** [comment]
Correct

**Comment by tomturner** [comment]
I have written it that this feature is turned off by default

**Comment by MiltonLn** [comment]
Can't you handle this creating the specific city or country on the tests that need them? i assume that you don't really need them for all the tests. That's the way i have handled this for django-auth groups for example.

**Comment by tomturner** [comment]
No I have to much data
