### ISSUE TITLE
Missing permission when tenant user tries to create object from TENANT_APPS

### ISSUE THREAD

**Issue by atodorov** [django-tenants/django-tenants#273]
In short I have a public schema which holds django.contrib.auth together will all other apps. Basically SHARE_APPS == INSTALLED_APPS. Then TENANT_APPS is a subset of that:

```
        TENANT_APPS = [
            # this is from the documentation
            'django.contrib.contenttypes',

            # the rest is a subset of INSTALLED_APPS, e.g. models which tenants should have access to, aka seeing only their own data
            'django.contrib.sites',

            'attachments',
            'django_comments',
            'modernrpc',
            'simple_history',

            'tcms.core.contrib.comments.apps.AppConfig',
            'tcms.core.contrib.linkreference',
            'tcms.management',
            'tcms.testcases.apps.AppConfig',
            'tcms.testplans.apps.AppConfig',
            'tcms.testruns.apps.AppConfig',
        ]
```

With this setup a regular user can access the tenant and view objects if they exist. However they are not able to create such objects. For example this user is missing the `testcases.add_testcase` permission.

I have narrowed down this to:

```
SELECT 
    "auth_permission"."id",
    "auth_permission"."name", 
    "auth_permission"."content_type_id", 
    "auth_permission"."codename" 
FROM "auth_permission" 
INNER JOIN "auth_group_permissions" ON ("auth_permission"."id" = "auth_group_permissions"."permission_id") 
INNER JOIN "auth_group" ON ("auth_group_permissions"."group_id" = "auth_group"."id") 
INNER JOIN "auth_user_groups" ON ("auth_group"."id" = "auth_user_groups"."group_id") 
INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") 
WHERE "auth_user_groups"."user_id" = 3428 
ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC
```

That is the SQL query which Django issues internally to figure out what kinds of permissions does the current user have assigned to them.

When issued against public schema it returns 235 objects, when issued against a tenant schema it returns 164 objects. The ones I'm looking for (with `@permissions_required`) are missing.

From what I can tell the `auth_permission` table has a foreign key to `django_content_type` and the contents of public.django_content_type and tenant.django_content_type are of course different. In this scenario the INNER JOIN above filters out permissions for which the content type ID doesn't match.

In the source code I was able to find comments about clearing ContentType cache and similar explanations about different IDs for the same model on the 2 schemas.

Given that I want to have all users and permissions controlled from the public schema is there any compelling reason to have 'django.contrib.contenttypes' in TENANT_APPS ?

**Comment by atodorov** [comment]
More info:

I have tested locally and removed the `contenttypes` application from TENANT_APPS and started with a clean DB. Permission problem was solved. I also tried  creating a related sequence of records on the two tenants and adding comments to them b/c django_comments uses ContentTypes - seems to work normally. All of the objects 9on the 2 schemas) have the same IDs but on each schema I was able to see only the comments which should be there. They didn't get mixed up.


@tomturner please clarify if you have more experience and/or insight into ContentTypes and permissions. It looks like I will be removing this from my configuration.

**Comment by 5starkarma** [comment]
This seems to be a bug in Django-tenants. I am having permissions issues as well. The permissions are not aligning with the models.

**Comment by 5starkarma** [comment]
Yeah, so the documentation is wrong. I hope someone clarifies what the use is of putting content types in both tenant and shared schemas because my permissions are all messed/mixed up when it is set like that.

**Comment by dperetti** [comment]
Also curious to know @tomturner insight. It makes sense for `django_content_type` to be unique and shared in the project.

**Comment by atodorov** [comment]
@tomturner I am looking back into permissions & contenttypes and noticed that despite you fixing this a long time ago the documentation is still not updated: 
![Screenshot_2022-03-11 Installation — django_tenants dev documentation](https://user-images.githubusercontent.com/1002300/157869754-de393ce6-00d5-4cf8-bb2e-6b39be4642c1.png)

Can you check if there's a problem with regenerating the documentation.
