### ISSUE TITLE
Help needed: how to sync table to all tenants after update of TENANT_APPS ?

### ISSUE THREAD

**Issue by atodorov** [django-tenants/django-tenants#308]
We've added a model called Bug (table bugs_bug) to the main application and it has been synced to the public schema. However when we deployed we forgot to add the new application to TENANT_APPS. 

In Postgres DB terminal I can see that tenants don't have this new table. Even after updating TENANT_APPS and redeploying migrate doesn't seem to detect the changes. It tells me that all migrations have been applied. Additionally `--list` doesn't seem to work either. 

Any idea how to sync only this 1 table to all existing schemas ?

**Comment by atodorov** [comment]
FTR I removed the migration from `django_migrations` table for each tenant and then re-run `manage.py migrate`

```
kiwi=> delete from <tenant-name>.django_migrations where app = 'bugs';
DELETE 1
```

**Comment by mcroni** [comment]
did u run migrate_schemas or just migrate

**Comment by atodorov** [comment]
We've always used `migrate` so far and it applied all pending migrations to all schemas. I tried both migrate & migrate_schemas after updating TENANT_APPS but I got the same result: no pending migrations to be applied. That's why I had to do the delete workaround above.

**Comment by tomturner** [comment]
For anyone looking at this later migrate and migrate_schemas do the same thing.
