### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by tomturner** [django-tenants/django-tenants#32]
What new features would people like to see?

**Comment by kosz85** [comment]
1. Parallel migrations
2. Tenant types #30
3. URL domain path prefix middleware instead of subdomain #28
4. Better docs for common problems
5. Built-in solution for shared authentication #9
6. Built-in base tests case that will create tenant on setup and delete on tear down.

**Comment by salvadormrf** [comment]
+1 for Parallel migrations
Add utility decorator to run migrations for tenants only.  

```python
def skip_public_schema(f):
    @wraps(f)
    def wrapper(apps, schema_editor):
        # Run migration for tenants only
        if schema_editor.connection.schema_name == get_public_schema_name():
            return
        return f(apps, schema_editor)
    return wrapper

# Example
@skip_public_schema
def create_access_admin_permission(apps, schema_editor):
    pass

class Migration(migrations.Migration):
    dependencies = [
    ]
    operations = [
        migrations.RunPython(create_access_admin_permission)
    ]
```

**Comment by tomturner** [comment]
@salvadormrf A pull request is welcome

**Comment by kosz85** [comment]
But is this decorator correct? App is shared or not, and it goes same with it's migrations. You shouldn't have to do such decorator - it's bad design. If you need it, then probably you should split your app into shared and tenant parts.
Your solution will do dummy migration, that does nothing. I'm against it.

**Comment by tomturner** [comment]
@kosz85 You got a point I haven't had the needed a decorator for migrations yet! 

@salvadormrf I agree to parallel migrations however I don't think the decorator is needed. Are you sure you are on the latest version as there was a bug which meant the migrations for every app

**Comment by kosz85** [comment]
@tomturner We will do that soon (probably this month), as we need it in our project, @cgenie will be responsible for it, so await good quality code :)

**Comment by tomturner** [comment]
Parallel migrations ticket is #38

**Comment by ivome** [comment]
@salvadormrf I don't think there is a need for the decorator. You should be able to use the `--tenant` or `--shared` options to run the migration only on tenants or only on public.

**Comment by salvadormrf** [comment]
We are using this for data migrations only on shared apps like contrib admin. Where a specific group needs to be created/modified for tenants only.

**Comment by kosz85** [comment]
@salvadormrf Still you can use dependencies and do it in external tenant app migration. But it's no problem if you use such decorator in your own projects. I just don't think this fit well as public solution. This is making dangerous hack for doing per tenant migrations, as you can easily change 'public' to ANY of schema names. But this starts to be data dependent migration (it depends on tenants listed in your DB), and not generic one. But maybe I'm too conservative.

**Comment by tomturner** [comment]
New release has been issued 1.1.0

**Comment by bartmika** [comment]
1. I would like to see this library to always try to support the latest **Django** out at the current time and make sure it supports **Python 3.4**.
2. I would like to see contact information for the main developer(s) of this project in the **readme**. This library is going to be an essential library for any business / company and generally the enterprise environment. Enterprise would like the security of knowing they can contact the main developer(s) of this project if any problems occur or they may have feature requests. 
3. I like the developer(s) to write in the **readme** a vision of what they can commit to this project. If an enterprise would use this library for their core technology, they would want to know this project will be around for a long time judging from the vision.

Thanks you kindly!

**Comment by tomturner** [comment]
@bartmika 

Hi @bartmika I am the main developer for django-tenants.
 I was in the the same boat as you about a year ago when I was looking at django-tenant-schemas I was getting no replies to any of my posts or pull request hence I copied the project.
 I am committed to django-tenants and it is an very important to my company as well.
My email address is listed in setup.py file. If you send me an email I can give you more contact details.

Regarding python 3.4 I was unware it didn't work until l last week

I hope that answers some of your questions

Tom

**Comment by kosz85** [comment]
I waited for you response @tomturner :)
My company is also heavily using django-tenants and get involved with this project from same reasons. I try to support project any free time I have, but for me it's good as it is now. If I have any need then I extend it, and share what can be easily shared.

1. I checked today Python 3.4.4 and it's working ok, so maybe FreeBSD or older version has some problems.
2. I can share my contact, but what for? Private consultations are paid ;) Github consultations are free.
3. It's more like what you expect here? This project is simple it has 1-5 features, it's working on production about 2 years already, performing very well. After some configuration you can more or less forget about it, and focus on implementing your app features.

**Comment by chimeno** [comment]
I would like to see in the README (or another visible place).

- Why a fork of another project.
- What are the differences with that project.
- Python and Django version supported

When looking at first there is no difference between projects.

Thanks!

**Comment by tomturner** [comment]
@chimeno

_Why a fork of another project._
  The parent project looked like dead. When I created this fork with the other project had no commits and was not answering my messaged, It was at the time that when Django 1.8 was being released. I needed Django 1.8 support and when I looked at the code it had lots of _if Django version = x_ which I didn't like. Hence the fork.

  
_What are the differences with that project._ 
The work almost the same however this has multiple domain name support. (I know this is the other project now). It also has a Parallel migrations which i don't believe is in the other project.

_Python and Django version supported _ This is on the home page it works works with Django 1.8 / 1.9

**Comment by kosz85** [comment]
It also is enhanced with some syntax sugar, so you can do:
```
with tenant:
   do code in that schema
```

It was proposed to the other project, but never responded as it was not active that time.

**Comment by chimeno** [comment]
@tomturner 
Thanks for your answers, and for your work here.
I meant that answers could be placed in the README (or other visible place) in order to new users catch the differences at once.

About the Python and Django versions, the README currently says:

> Requirements
>
>Django 1.8 if you want to use 1.7 or lower please use django-tenant-schemas.
>PostgreSQL

What leaves some answer in the air: ¿is it works with Python3, is it works with Django 1.9 ?
Maybe I've missed something (altough I looked it some times).

**Comment by bartmika** [comment]
I would like to see the following features:

- A **reverse** function tailed for returning a URL based on tenant. (see: #87)
- Allow testing **public** and **tenant** schemas in Unit Tests. (see: #88)
- Allow creation of new schemas in Unit Tests. Currently you are only limited to using the ``test`` schema and you are not allowed to create any more. (see: #86)

**Comment by stephane** [comment]
It's painful for newcomers to read the code of [django-tenant-schemas](https://github.com/bernardopires/django-tenant-schemas) and [django-tenants](https://github.com/tomturner/django-tenants) to compare them.

@tomturner 
Have you considered joining forces by merging projects?

**Comment by tomturner** [comment]
@stephane I forked DTS for a reason. I tried to get a patch for a new version Django 1.8 into DTS which lots of us were desperate for. I tried to contact DTS with no luck so after a month I created DT. Later he emailed to say he was busy doing exams hence wasn't working on DTS at that time. Lots of people thought he had given up on DTS. I have no plans in getting rid of this project or merging back to DTS as this is a key part of my businesses. Hope this helps

**Comment by stephane** [comment]
@tomturner, I understand. Could you add your comment https://github.com/tomturner/django-tenants/issues/32#issuecomment-218271090 to the README, please?
It will be very helpful. Thank you.

BTW the [setup.py](https://github.com/bernardopires/django-tenant-schemas/blob/master/setup.py) of [django-tenant-schemas](https://github.com/bernardopires/django-tenant-schemas) requires Django 1.8+.

**Comment by tomturner** [comment]
@stephane DTS has since been modified lots. The code base was a mess because it allowed for different version of Django. The first thing I did was remove the old version support from DT. I saw you asked about Django 1,11 on DJT  I plan to the change to DT the week Django 1.11 gets released as I want to use it in my projects.

**Comment by tomturner** [comment]
@stephane  Infact your pull request to DTS will be very usefully thank you. If you want to do the Pull request to DT you are more than welcome however I won't merge it until Django 1.11 becomes live

**Comment by stephane** [comment]
I don't understand your last comment https://github.com/tomturner/django-tenants/issues/32#issuecomment-288414065, I was just asking for more informations in README.

For now, I prefer to use DTS (suspicious middleware, storage, etc) than DT. I don't have time to write PRs for both projects so I choose one...

**Comment by MiltonLn** [comment]
I agree with the README update request, it'll be nice to the people to know the differences between projects.

**Comment by jameskirsop** [comment]
I'm unsure if this is already a feature and I'm missing something in the docs, or it's not implemented - but I'd love to see the ability to use `./manage.py shell` and interact with a particular tenancy for prototyping/testing/development purposes.

I use the shell frequently to quickly check that functions are returning the values I expect after writing them before moving to implementing them elsewhere.

**Comment by kosz85** [comment]
Just do `Tenant.objects.get(<your-query>).activate()` at shell, or you can add it to starting scripts in  `IPython`, or smth similar. That's really not an issue, I use my shell often too.
