### ISSUE TITLE
What Postgres versions are supported?

### ISSUE THREAD

**Issue by thismatters** [django-tenants/django-tenants#338]
It looks like [django-tenant-schemas](https://github.com/bernardopires/django-tenant-schemas) stops support at PostgreSQL 9.6, how about django-tenants?

edit: `.travis.yml` uses PostgreSQL v9.6 for testing...

**Comment by atodorov** [comment]
I've used both Postgres 10 and Postgres 12 for testing. Currently using 12 in production.

**Comment by tomturner** [comment]
@atodorov Welcome the pull request
