### ISSUE TITLE
How to login users from public schema login page and redirect to tenant instead of directly from subdomain login page?

### ISSUE THREAD

**Issue by gabrielsaldana** [django-tenants/django-tenants#414]
I'd like to have a login page in my public schema where a user logs in and redirects to their tenant's main view.

So I've seen the documentation on how to redirect a user to a newly created tenant subdomain. But what about normal login? I don't expect the users to remember their subdomain, so I'd like to have a login page in my main public domain, that will redirect and log in the user to their subdomain.

For example, I go to `www.mycoolapp.com` see the login button, click it, a form loads, I type in my username/password, click login button and now I get redirected to `mytenant.mycoolapp.com` logged in and loads my main dashboard.

I don't want cross-tenant access, I just need cross-tenant user lookup so I can redirect `dude@gmail.com` to his `mytenantspace.mycoolapp.com` upon login without having the user remember the subdomain url to find the right login page.

Do I have to register users both on public and tenant schemas and keep them in sync? Or is there a way to lookup users across all my tenants and redirect to their subdomain upon successful login?

**Comment by adnathanail** [comment]
I keep my users in the public schema for this exact reason - although this does then mean you can't have foreign keys _from_ user to a table in the tenant schema

**Comment by tomturner** [comment]
Take a look at this project which is an addon to Django Tenants https://github.com/Corvia/django-tenant-users it might help.

**Comment by adnathanail** [comment]
@hmamman interesting! Can you do foreign keys in both directions?

As in I can have a foreign key _to_ User just not _from_ User

This is fine for me:
```python
class AModelInTheTenantSchema:
	user = models.ForeignKey(User)
```

This is not:
```python
class User:
	favourite_thing = models.ForeignKey(AModelInTheTenantSchema)
```

**Comment by hmamman** [comment]
> This is not:
> 
> ```python
> class User:
> 	favourite_thing = models.ForeignKey(AModelInTheTenantSchema)
> ```

I guess you are right! I will find out

**Comment by bouhaddiamine** [comment]
> Take a look at this project which is an addon to Django Tenants https://github.com/Corvia/django-tenant-users it might help.

i tried this solution but we got some errors, can you double check  the issues please in django-tenant-users  last issue

**Comment by jayjunkyu** [comment]
are there any good solutions on this besides trying to implement `django-tenant-users`?

**Comment by tomturner** [comment]
@jayjunkyu  Write your own version it wouldn't be that hard to do. As long as the user table is not in the tenant app it should be quite easy to do.

**Comment by jayjunkyu** [comment]
so my users are in the tenant app is my problem

**Comment by bouhaddiamine** [comment]
I decided to stop using Django and back to PHP/Laravel

Le mer. 23 mars 2022 à 06:04, Joseph Jeong ***@***.***> a
écrit :
