### ISSUE TITLE
Is it possible to access tenants on same domain? 

### ISSUE THREAD

**Issue by experimarketing** [django-tenants/django-tenants#432]
I am using DRF and I want to access endpoints on the same domain. 

For example, mydomain.com/tenant1/api/, mydomain.com/tenant2/api.

Is that possible?

**Comment by DataGreed** [comment]
Same question here - having multiple domains is not convenient in some cases, e.g. when one user has access to multiple tenants and needs to have auth data shared between domains or in cases when you use subdomains to separate products, not tenants.

Is it possible to setup tenant separation by URL part that goes domain name? E.g. `/tenant1`/, `/tenant2/`?

**Comment by mcroni** [comment]
@experimarketing are you referring to subdomains ?

**Comment by DataGreed** [comment]
@mcroni uhm, the docs states that tenants has to be in their own subdomains. The question is how to make it work on the same domain.

**Comment by tomturner** [comment]
This is coming in the next release

**Comment by DataGreed** [comment]
@tomturner that's awesome, thanks!

**Comment by podplatnikm** [comment]
@hmamman Hey. Can you provide more info on how you did that with the current release? For my particular use case, the use of subdomains is not possible/viable, so I would like to explore your solution.

**Comment by hmamman** [comment]
The application I am working on has the front-end developed in Vuejs while the back-end is django-rest. We also use [django-tenant-users](https://github.com/Corvia/django-tenant-users) because we want to maintain a single userbase for all tenants which also allows a user to belong to more than one tenant as in our case. So, when a user login from the frontend, his tenant is identified and sent back as part of the response. This tenant is then stored on Vuex store. The tenant domain is then sent on subsequent request sin a custom HTTP header (TENANT-DOMAIN).

**Comment by tomturner** [comment]
Done

**Comment by AllenEllis** [comment]
@tomturner Is there a commit or branch for this new feature that I can look at?

I'm designing our SaaS's architecture now and we're needing to decide whether we need to use unique subdomains per tenant (would prefer not to).

Thanks!

**Comment by darkrace** [comment]
@tomturner can you give us any example or tutorial... how we can get different tenant using path instead of subdomains?

**Comment by tomturner** [comment]
Please see https://github.com/django-tenants/django-tenants/tree/master/examples/tenant_subfolder_tutorial

**Comment by darkrace** [comment]
I have run this example and created 2 tenant using ./manage.py create_tenant after that i runserver and it returns 404 error on 127.0.0.1:8000 or on tenant domain too.. i need to call tenant other than subdomain...

**Comment by bouhaddiamine** [comment]
> The application I am working on has front-end developed in [Nuxt.js](https://nuxtjs.org/) while the back-end is django-Rest. We also use [django-tenant-users](https://github.com/Corvia/django-tenant-users) because we want to maintain a single _userbase_ for all tenants which also allows a user to belong to more than one tenant as in our case. So, when a user login from the frontend, his tenant is identified and sent back as part of the response. This tenant is then stored on Vuex store. The tenant domain is then sent on subsequent request as a custom HTTP header (TENANT-DOMAIN) using axios.
> 
> At the backend, a custom middleware is created following suggestion in the [django-tenant-schema](https://django-tenant-schemas.readthedocs.io/en/latest/advanced_usage.html) documentation. The middleware is a subclass of **TenantMainMiddleware** which override its `hostname_from_request` method like so:
> 
> ```
> from django_tenants.middleware import TenantMainMiddleware
> class XHeaderTenantMiddleware(TenantMainMiddleware):
>     @staticmethod
>     def hostname_from_request(request):
>         """ Extracts hostname from request. Used for custom requests filtering.
>             By default removes the request's port and common prefixes.
>         """
>         hostname = remove_www(request.get_host().split(':')[0])
>         tenant_domain = request.META.get('HTTP_TENANT_DOMAIN')
>         if tenant_domain:
>             return tenant_domain
>         return hostname
> ```
> 
> If an HTTP header is sent with the tenant domain, we return it otherwise we return the hostname. This ways we have two subdomain identification strategies in place.
> 
> This middleware replaces `django_tenants.middleware.main.TenantMainMiddleware` in `settings.py` like so:
> `MIDDLEWARE = [ 'apps.middleware.XHeaderTenantMiddleware', ]`
> 
> To make sure the custom HTTP header is accommodated, we added it to cors headers:
> `CORS_ALLOW_HEADERS = list(default_headers) + [ 'TENANT-DOMAIN', ]`
> 
> Dont forget to install `django-cors-headers`
> 
> Let me know if this helps.

i need your help please

**Comment by hmamman** [comment]
@bouhaddiamine I will be glad to help. What is the matter?
