### ISSUE TITLE
Will it work with amazon redshift?

### ISSUE THREAD

**Issue by DataGreed** [django-tenants/django-tenants#433]
Will this module work with amazon redshift using django-redshift-backend or something similar?

Redshift seems to have schemas, too https://docs.aws.amazon.com/redshift/latest/dg/r_Schemas_and_tables.html

**Comment by mcroni** [comment]
I don't think so as this package is designed to work with Postgres

**Comment by tomturner** [comment]
Nope it won't work. This will only work with PostgreSQL

**Comment by DataGreed** [comment]
@tomturner why won't it? [Redshift based on PostgreSQL 8.0.2](https://docs.aws.amazon.com/redshift/latest/dg/c_redshift-and-postgres-sql.html)

**Comment by tomturner** [comment]
When I googled it it looked like you needed a custom backend called django-redshift-backend if that is the case you will find it hard to get it to work as Django Tenants uses a custom backend

**Comment by DataGreed** [comment]
@tomturner makes sense. Thanks for the clarification
