### ISSUE TITLE
Incompatible with Django 3.1(beta)

### ISSUE THREAD

**Issue by e-mojo** [django-tenants/django-tenants#434]
Hi,
I've just tried installing the beta version of Django 3.1 and I got the following response:
`ERROR: django-tenants 3.1.0 has requirement Django<3.1,>=2.1, but you'll have django 3.1b1 which is incompatible.`

Did you look into the compatibility with 3.1 and is there a rough timeline for preparing django-tenants for 3.1? Of course no pressure, but should you have looked into this, then I would love to know!

Let me end this with a huge thanks for releasing this app, vital for my tool!
Best,

Erwin

**Comment by tomturner** [comment]
As soon as django 3.1 is out I will make it work. As I will want it for my project

**Comment by infosrabah** [comment]
LoL, i was about to ask the same question ...

Thank you Tom

**Comment by bartmika** [comment]
Thank you Tom!

**Comment by infosrabah** [comment]
Ohh, really Sorry.

Error typing.

Thank you e-mojo.

**Comment by tomturner** [comment]
There is now a branch for Django 3.1

**Comment by infosrabah** [comment]
Thank you tom,

another one please, based on the comment I red, is it soon that django-tenants will support tenants by their URLs not just subdomain ?. like www.mydomain/tenant1

thank you
