### ISSUE TITLE
Is it worth implementing a dummy table to store the tenant info in each schema

### ISSUE THREAD

**Issue by variable** [django-tenants/django-tenants#440]
Maybe this has been asked or a completely stupid idea but I will give a go:

Currently we can get the tenant object from the request object. But sometimes it's impossible to access this info deep within some functions that doesn't accept the request parameters. 

My idea is to create a dummy table to store some basic info about the tenant, eg. the name of it.
So that I can in anywhere to be able to identify the tenant information without needing to access the request object.

eg.
```python
def get_tenant_name():
    DummyTable.objects.first().name
```

We can use the middleware to pre-populate the values.

Totally aware of the extra database operations, hopefully the trade off is worth doing?

**Comment by tomturner** [comment]
I had to do this in my project. I created a table called TenantLink. which I have one record per tenant. I populate the one row on creation of that tenant. I don’t use it very often however once or twice I needed it when the request object isn’t available. For some reason I couldn’t put a foreign key to the tenant so I store the id. Personally I wouldn’t store the name in case later you decide to change that tenant schema name.

**Comment by variable** [comment]
Yeah, name was just for example. Idea is just to identify which tenant the code is running for.

**Comment by jcass77** [comment]
We do this in our project as well - just include `TenantMixin` in your model class definition.

This also allows you to use the context manager to safely switch between tenants using something like:
```python
with Tenant.objects.get(schema_name='my_tenant'):
    # ...do processing here
   pass
```

**Comment by variable** [comment]
> We do this in our project as well - just include `TenantMixin` in your model class definition.
> 
> This also allows you to use the context manager to safely switch between tenants using something like:
> 
> ```python
> with DummyTable.objects.get(schema_name='my_tenant'):
>     # ...do processing here
>    pass
> ```

Hello sorry I am bit lost on using the mixin, it requires to know the schema_name but the point of having the dummy table is to find out the tenant? Maybe I misunderstood something?

Cheers!
