### ISSUE TITLE
Migrate tenant schema doesn't create table

### ISSUE THREAD

**Issue by gityopie** [django-tenants/django-tenants#443]
Hi 👋 

Thanks for this great packages

I'm wondering If I missed something or I don't followed the document correctly

I have an issue where my models doesn't migrated on target schema.
(for information, I used the package `django-tenants` with `django-tenant-users` on Django 3.0.7)

By following the sample app given on each package, it works fine until I added a new app.
After executed these two commands
```
$ python manage.py makemigrations
Migrations for 'tenant_only':
  tenant_only/migrations/0001_initial.py
    - Create model TableOne
    - Create model TableTwo
```
 and then 
```
$ python manage.py migrate_schemas --shared
[standard:public] === Starting migration
[standard:public] Operations to perform:
[standard:public]   Apply all migrations: admin, auth, contenttypes, customers, permissions, sessions, tenant_only, users
[standard:public] Running migrations:
[standard:public]   Applying tenant_only.0001_initial...
[standard:public]  OK
```
and then i checked the database,  I don't see the expected models migrated on the schemas.

`mytenant_site=# \dt tenant1_1592719483.*`
                                     List of relations
|      Schema       |                        Name                        | Type  |  Owner   |
|---------------|-----------------------------------|-------|---------|
| tenant1_1592719483 | auth_group                                         | table | yopi |
| tenant1_1592719483 | auth_group_permissions                             | table | yopi |
| tenant1_1592719483 | auth_permission                                    | table | yopi |
| tenant1_1592719483 | django_content_type                                | table | yopi |
| tenant1_1592719483 | django_migrations                                  | table | yopi |
| tenant1_1592719483 | permissions_usertenantpermissions                  | table | yopi |
| tenant1_1592719483 | permissions_usertenantpermissions_groups           | table | yopi |
| tenant1_1592719483 | permissions_usertenantpermissions_user_permissions | table | yopi |
(8 rows)

`mytenant_site=# \dt tenant2_1592719483.*`
                                     List of relations
|       Schema       |                        Name                        | Type  |  Owner |   
|----------------|-----------------------------------|------|---------|
| tenant2_1592719483 | auth_group                                         | table | yopi |
| tenant2_1592719483 | auth_group_permissions                             | table | yopi |
| tenant2_1592719483 | auth_permission                                    | table | yopi |
| tenant2_1592719483 | django_content_type                                | table | yopi |
| tenant2_1592719483 | django_migrations                                  | table | yopi |
| tenant2_1592719483 | permissions_usertenantpermissions                  | table | yopi |
| tenant2_1592719483 | permissions_usertenantpermissions_groups           | table | yopi |
| tenant2_1592719483 | permissions_usertenantpermissions_user_permissions | table | yopi |
(8 rows)

`mytenant_site=# \dt public.*`
                               List of relations
| Schema |                        Name                        | Type  |  Owner   |
|--------|-----------------------------------|-------|----------|
| public | auth_group                                         | table | yopi |
| public | auth_group_permissions                             | table | yopi |
| public | auth_permission                                    | table | yopi |
| public | customers_client                                   | table | yopi |
| public | customers_domain                                   | table | yopi |
| public | django_admin_log                                   | table | yopi |
| public | django_content_type                                | table | yopi |
| public | django_migrations                                  | table | yopi |
| public | django_session                                     | table | yopi |
| public | permissions_usertenantpermissions                  | table | yopi |
| public | permissions_usertenantpermissions_groups           | table | yopi |
| public | permissions_usertenantpermissions_user_permissions | table | yopi |
| public | users_tenantuser                                   | table | yopi |
| public | users_tenantuser_tenants                           | table | yopi |
(14 rows)

Here is my `settings.py`
```
...
AUTH_USER_MODEL = 'users.TenantUser'

# Application definition

SHARED_APPS = (
    'django_tenants',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tenant_users.permissions',
    'tenant_users.tenants',
    'core.apps.CoreConfig',
    'customers.apps.CustomersConfig',
    'users.apps.UsersConfig',
)

TENANT_APPS = (
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'tenant_users.permissions',
    'tenant_only.apps.TenantOnlyConfig',
)

TENANT_MODEL = 'customers.Client'
TENANT_DOMAIN_MODEL = 'customers.Domain'

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

MIDDLEWARE = [
    'django_tenants.middleware.TenantMiddleware',
   ...
]
...
```

I also try to run the provision tenant and got this message
```
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/yopi/Workspaces/python/Django/mytenant_site/.venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/yopi/Workspaces/python/Django/mytenant_site/.venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/yopi/Workspaces/python/Django/mytenant_site/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/yopi/Workspaces/python/Django/mytenant_site/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/Users/yopi/Workspaces/python/Django/mytenant_site/mytenant_site/core/management/commands/tenant_provision.py", line 9, in handle
    provision_tenant("Tenant1", "tenant1", "tenant1@example.com")
  File "/Users/yopi/Workspaces/python/Django/mytenant_site/.venv/lib/python3.7/site-packages/tenant_users/tenants/tasks.py", line 34, in provision_tenant
    raise ExistsError("Tenant URL already exists.")
tenant_users.tenants.models.ExistsError: Tenant URL already exists.
```

Did I missed something?

If start it with a new database, it works fine.

Thanks in advance!

**Comment by gityopie** [comment]
Found the solution on this document https://django-tenants.readthedocs.io/en/latest/use.html#management-commands

Thank you!

**Comment by yogeshdmca** [comment]
sorl.thumbnail migration also not work. 
0001_initial.py available with sorl.thumbnail. still getting error.

`django.db.utils.ProgrammingError: relation "thumbnail_kvstore" does not exist
LINE 1: ..._kvstore"."key", "thumbnail_kvstore"."value" FROM "thumbnail...`

![image](https://user-images.githubusercontent.com/3122284/87232961-be3d4b00-c3e0-11ea-8439-6547022a73c4.png)
