### ISSUE TITLE
Running scheduled functions per tenant

### ISSUE THREAD

**Issue by experimarketing** [django-tenants/django-tenants#444]
If using a scheduler [1],  how would I make sure it runs for each tenant? 

For example, if I have a tenant class/model called EmailsToSend.

And in that model I use the scheduler roughly like this: 

`
import schedule
import time

EmailsToSend(Models.Model):
   email_content = models.TextField()

   def job():
       send_current_emails()

schedule.every(10).minutes.do(EmailsToSend.job)

`

And if this doesn't work with django-tenants, how would you recommend I schedule tasks to be done that need to happen for each tenant?

[1] https://github.com/dbader/schedule

**Comment by mcroni** [comment]
I use celerybeat for this kinda stuffs.
```
app.conf.beat_schedule = {
     'add-every-monday-morning': {
         'task': 'hr.tasks.tester',
         'schedule': 30.0,
     },
    # 'run_auto_pilot': {
    #     'task': 'payroll.tasks.auto_pilot',
    #     'schedule': 10.0,
    # }

}
```
then you can a code like this in your tasks file
```

@app.task
def tester():
    for tenant in get_tenant_model().objects.exclude(schema_name='public'):
        with tenant_context(tenant):
            print("do whatever you want to do here")
```
