### ISSUE TITLE
Specific field for specific tenant.

### ISSUE THREAD

**Issue by saileshkush95** [django-tenants/django-tenants#446]
This package is already awesome. So thanks to,  all the contributors who spent their valuable time for this awesome packages. This package is already providing lots of flexibility but i think, but still this is missing somethings. 
For example.

Suppose I've model called contact and it contain four field some things like this.

```
class Contact(models.Model):
    full_name = models.CharField(..)
    email = models.EmailField(...)
    subject = models.CharField(...)
    message = models.TextField(...)
```
for most of the tenant this is enough for but some reasons, only for some tenant we also need to include address field too. 

so my question is how can I override this model for specific tenant so that i can include only address for for specific tenant. 
If i assume contact as a app is there  any way to override or replace contact app only for specific tenant.

if this features is included by default it will be awesome.  
At last thanks for this amazing package and happy coding.

**Comment by mcroni** [comment]
i think adding an extra field to this model to serve that special tenant wouldn't harm the architecture of your app.

**Comment by saileshkush95** [comment]
@mcroni thank you for you valuable time. But my requirement is not just a field. I want some thing, so that some app is only available for some tenant.

**Comment by tomturner** [comment]
Sounds like you need to create addon.  I would create a new table called Addons that is public.  Then put a many to many field on the Tenant model to that Addons. Then you can query if that feature needs turning on or off.  I had to do this for my project.

**Comment by 5eyegeo** [comment]
@tomturner can you please explain little bit more so i cant start working on this. For example suppose i have two app in my project, called blog, and eCommerce, now how can i enable or disable app for specific tenant. i also want to prevent from migrating to database of disable app.

**Comment by saileshkush95** [comment]
@tomturner can you please explain little bit more so i cant start working on this. For example suppose i have two app in my project, called blog, and eCommerce, now how can i enable or disable app for specific tenant. i also want to prevent from migrating to database of disable app.

**Comment by tomturner** [comment]
see #494. Think this sorts the problem out
