### ISSUE TITLE
django-tenants and connection pooler?

### ISSUE THREAD

**Issue by thenewguy** [django-tenants/django-tenants#447]
What options are out there for postgres connection pooling when using schemas via django-tenants?  I've always used pgbouncer in transaction mode but have come to find out that isn't possible when using schemas.

Are there any recommendations, experiences, or best practices that could be shared?

**Comment by jcass77** [comment]
I have not come across this pgbouncer limitation - could you cite a reference in the official docs or other sources that you are using please?

**Comment by thenewguy** [comment]
Perhaps I am wrong then...  You have been using it without any issue in transaction pooling mode?

The first issue I noticed was with db backed sessions being lost during browsing seemingly without pattern.  This seemed to be resolved by changing from transaction pooling to session pooling but I haven't tested it much yet.  I am not sure the issue is solved.

Session pooling has not seemed to fix long running celery tasks from losing the schema they were working against - i.e. they start the job fetching the db record and then get an IntegrityError on commit stating the records previously fetched did not exist.  Oddly, logs would report the expected schema name.  However, the "missing" records are viewable via the admin before and after the jobs. Anecdotal I guess... but I came to the conclusion it was a transaction pooling issue.

I found these two issues:
- https://github.com/pgbouncer/pgbouncer/issues/246
- https://github.com/pgbouncer/pgbouncer/pull/73

Which specifically discuss schema based multi-tenancy and the pgbouncer team response seemed to be not interested in handling the use-case.

**Comment by jcass77** [comment]
I have been using transaction pooling with pgbouncer and dramatiq (a background task processing library comparable to celery), without any issues for close to 2 years.

We have only had one `public` tenant for most of that time though, so I am not sure if anything will change as we on-board more tenants in future?

Have you tried [disabling server-side cursors](https://docs.djangoproject.com/en/2.2/ref/databases/#transaction-pooling-and-server-side-cursors)?

**Comment by thenewguy** [comment]
I hadn't disabled server-side cursors - will give that a try now

**Comment by thenewguy** [comment]
I am going to close this issue as your 2 years is a fairly long time not to hit any issues =)  thanks for the wisdom.

**Comment by thenewguy** [comment]
I forgot to write back but I just wanted to leave a note for others that find it - we were able to consistently demonstrate the lost session issue when using pgpooler in transaction mode with database backed sessions.  This was the only easily observable problem, but since it exists I am pretty confident that other issues would present but be difficult to track down.

Swapping to session mode fixed it.  Everyone has been really helpful while working with django-tenants so I wanted to share what I could =)

**Comment by JelteF** [comment]
FYI if you install Citus in your database you can use pgbouncer in transaction pooling mode too, by changing `track_extra_parameters`
```
track_extra_parameters=search_path,IntervalStyle
```

Docs: https://www.pgbouncer.org/config.html#track_extra_parameters

**Comment by aiseei** [comment]
@JelteF . 
Hi. just came across this . we dont use CITUS but being able to use pgbouncer with django-tenants would be really great. so just to confirm that installing citus lets use transaction mode in pgbouncer ?
your clarification would readlly help !
