### ISSUE TITLE
How to properly setup aws in this packages

### ISSUE THREAD

**Issue by saileshkush95** [django-tenants/django-tenants#448]
I didn't find any documentation that how can i setup aws properly. to storing media files and static files.

**Comment by tomturner** [comment]
Please can i have more details. Have you go different static files per tenant? Regarding media I personally use Django-private-storages https://pypi.org/project/django-private-storage/

**Comment by saileshkush95** [comment]
Thank you for your suggestion. Bye the way I'm using tenant aware staticfiles
