### ISSUE TITLE
Global Admin to Manage All Tenants

### ISSUE THREAD

**Issue by bugraaydogar** [django-tenants/django-tenants#453]
Hi folks,

I'm considerable new to Django and I wanted to kick start my SAAS application. I think, django-tenants is great library and I already get started. Basically, the requirement I have is following;

- A global admin page/account to add, delete, change, inspect the all data in all tenants.
- Admin page/account for related tenant (This is already possible)

I was trying to figure out how to implement the first one and I came across with "django-tenant-users" projects but I am not really sure if it focuses to solve the problem I described. What I understood from their description is that, they are trying to solve the problem which is "the user may belong to different tenants at the same time". In the meantime, I came across with following stackoverflow question (https://stackoverflow.com/questions/50133875/multi-tenant-schemasdynamic-api-routing-using-django-restframework) where the response also answers my question but I do not have any idea how to implement this.

Quote from the mentioned response;

> First start with admin and their privileges; for the above requirement, I have two admin roles: tenants_admin, tenant_admin.
Here, tenants_admin (who serve the product) are able to manage tenants(individual company who buy the product); tenants_admin can manipulate data of tenants and they are located at tables in public schema.
Now coming to tenant_admin, who has privilege over data of tenant users (let's say employees in single company).

The idea is interesting for me but I do not know how to implement this. What do you suggest to follow ? I believe, I'm not the only one who came across with this issue. I'm open to any suggestions.

Thanks a lot,
Bugra

**Comment by tomturner** [comment]
Yes it is possible to do. I have done in my app without the need for django tenant users.  I have written a custom admin area that queries certain info from each tenant. That app is in the public area.

**Comment by bugraaydogar** [comment]
Hey Tom,

Thanks for the info. I will take this suggestion with me and try to implement.
