### ISSUE TITLE
Handle user changing subdomain in address bar.

### ISSUE THREAD

**Issue by andyp05** [django-tenants/django-tenants#456]
I am trying to force a re-login if a logged in user changes a sub-domain in the browser's address bar. I have tried using a UserPassesTestMixin to track if the request.get_host() changes or is not authenticated. I am setting request.session.get('subdomain') at login. I need a UserPassesTestMixin for other app related reasons.

        if not request.user.is_authenticated or request.session.get('subdomain') != request.get_host():
            return False

But it seems that get_host() does not update or some other thing is going on that the login screen is not displayed. Returning False when a new subdomain has been changed gives me:

`ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine`

I have two scenarios:
1. Authenticated user edits subdomain to another subdomain they have access to.
2. Authenticated user edits subdomain to another subdomain they do not have access to.

Is there a best practice to handling this? Any advice would be appreciated.

Thanks

**Comment by tomturner** [comment]
Where yours user table?

**Comment by andyp05** [comment]
In the public schema.
After more testing, if I add the LoginRequiredMixin before my UserPassesTestMixin, it seems to work fine.

**Comment by tomturner** [comment]
Ok
