### ISSUE TITLE
How to get access to tenant schema in a view that gets called from a callback webhook

### ISSUE THREAD

**Issue by Abdoulrasheed** [django-tenants/django-tenants#459]
I am sending SMS Notification to users, the API will send back delivery status to one of my views. 

I need to get the tenant that sends that SMS in the callback view. below is my view

```
@method_decorator(csrf_exempt, name="dispatch")
class SMSDeliveryCallBackHook(View):
    def post(self, request):
        data = request.POST
        phone = data["phoneNumber"]
        messageID = data["id"]
        status = data["status"]
        network = data["networkCode"]

        message = Outbox.objects.filter(recipients__phone=phone).last()
        delivery_obj = MessageDeliveryStatus.objects.filter(message=message).first()
        delivery_obj.status = status
        delivery_obj.save()
        return HttpResponse("done")
```

**Comment by tomturner** [comment]
Can you not send extra data in the SMS message with the tenant_id.  If you can't do that can you not have a public table and store the tenant_id against the message id

**Comment by Abdoulrasheed** [comment]
> Can you not send extra data in the SMS message with the tenant_id

I am afraid, I can't do that.

But I'll try to see if the latter is possible and update you.

Regards

**Comment by Abdoulrasheed** [comment]
I go with storing the tenant_id against the message ID in a public tenant table.
