### ISSUE TITLE
While code supports Django 3.1 the PyPI release doesn't

### ISSUE THREAD

**Issue by mikicz** [django-tenants/django-tenants#466]
The issue is on this line https://github.com/django-tenants/django-tenants/blob/master/setup.py#L55, it still limits Django to <3.1, even though the code was updated  to support Django 3.1

**Comment by tomturner** [comment]
@mikicz thanks

**Comment by tomturner** [comment]
3.2.1 now released with that fix

**Comment by mikicz** [comment]
Thank you for releasing a new version!
