### ISSUE TITLE
 'django_tenants.postgresql_backend' isn't an available database backend.

### ISSUE THREAD

**Issue by erdmin** [django-tenants/django-tenants#468]
`django.core.exceptions.ImproperlyConfigured: 'django_tenants.postgresql_backend' isn't an available database backend.`

Fresh Installation Project
Django | 3.1 | 
django-tenants | 3.2.1 | 

Getting this error and I can't create app.
Any advice , please ?

**Comment by erdmin** [comment]
Reinstalled and worked.

**Comment by Dank-del** [comment]
i reinstalled too.. following this thread, yet I got the error



```
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: ('django_tenants.postgresql_backend',) isn't an available database backend or couldn't be imported. Check the above exception. To use one of the built-in backends, use 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'
```
