### ISSUE TITLE
reverse urls from public scope urls

### ISSUE THREAD

**Issue by JuliusJacobitz** [django-tenants/django-tenants#469]
Hi there, 
in my case I'm writing tests for a django app and I want to reverse some urls. It all works fine with most urls. But somehow I can't reverse urls from the src.proj.urls_public.py which includes the public scope URL configuration. 

The pattern looks like this: 

`urlpatterns = [
    path(
        "api/sth-exists/<str:id>/",
        shared_views.sth_exists,
        name="sth-exists",
    )]`

with `reverse("sth-exists")` i get this error: 

```
raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'sth-exists' not found. 'sth-exists' is not a valid view function or pattern name.
```

Thank you for any help :)

**Comment by JuliusJacobitz** [comment]
Thank you very much! @Ngahu

**Comment by matkeng** [comment]
Thanks, I am using this in a custom template tag as:
`# myapp/templatetags/tenant_tags.py

from django import template
from django.conf import settings
from django.urls import reverse, reverse_lazy

register = template.Library()

@register.simple_tag
def public_url(url_name):
    args=None,
    kwargs=None
    current_app=None
    return "http://testsite.io:8000" + reverse(url_name, urlconf=settings.PUBLIC_SCHEMA_URLCONF)`
