### ISSUE TITLE
Explicit API to set and query the tenant

### ISSUE THREAD

**Issue by suriya** [django-tenants/django-tenants#47]
At present, it looks like the tenant can be set in three ways:

1) `./manage.py tenant_command` which sets the tenant in `django_tenants.management.commands.tenant_command.Command.handle`
2) The user invoking the `django_tenants.utils.tenant_context` context manager
3) Most importantly, for each request by `django_tenants.middleware.TenantMiddleware`.

The method to know the current tenant seems to be accessing `connection.tenant` in all three situations or `request.tenant` in the third case.

It would be good to explicitly document and provide an API to query the current tenant. `connection.tenant` does not seem to be a good method because tenants can be used for more than just deciding the database schema path. The use of `request.urlconf` based on the requested tenant is already an example. Other users might have their own uses for tenant specific logic.

My suggestion is to create a class that provides an authoritative API to set and get the tenant. `connection.tenant` and `request.tenant` are simply convenient ways to get the current tenant.

**Comment by kosz85** [comment]
What you want to accomplish?
You can set tenant by fetching it and call `tenant.activate()`, if you want such shortcut to not use `connection` directly, you can add classmethod `Tenant.get_current()`, and I think it's more then enough.
`connection.tenant` ? You can use it to get tenant, and to set anyway.

**Comment by ivome** [comment]
We could add a utility function `get_current_tenant()` that returns the current tenant. Or we could add it to the `TenantMixin`. That way you don't have `connection.tenant` references all over the codebase. I was thinking about that too, actually. Is that what you mean? 
For setting the tenant, I think `TenantMixin.activate()` does the job.

**Comment by kosz85** [comment]
I had same thoughts, I also dislike using connection directly. `TenantMixin` is good place for that. I would suggest name `current` as a property or `get_current()`.

**Comment by suriya** [comment]
I did not know about `TenantMixin.activate()`. I was using `django_tenants.utils.tenant_context` until now.

As the two of you have mentioned, I also dislike having `connection.tenant` all over the place. That's that point of this ticket. I want to set/get the tenant and the fact that it is tied to the connection is incidental.

**Comment by BillBrower** [comment]
Has there been any progress on this issue since 2015?

**Comment by tomturner** [comment]
Need to create docs on this
