### ISSUE TITLE
Accesss to schema name in migration.py when executing migrate_schemas

### ISSUE THREAD

**Issue by andyp05** [django-tenants/django-tenants#471]
I am trying to create a trigger and I have added the raw sql to the migration file.

`migrations.RunSQL('CREATE TRIGGER audit_table AFTER INSERT OR UPDATE OR DELETE ON...')`

This runs fine when I run migrate_schemas. The problem is that postgreSQL has an issue during manual update of the tables such as in pgAdmin because the trigger does not have the schema name defined with it. PostgreSQL wants:

`CREATE TRIGGER SCHEMA.audit_table AFTER INSERT OR UPDATE OR DELETE ON...`

How do I get the schema name to be visible in the migration.py file so I can append it to the SQL?

Thanks for any suggestions.

**Comment by mmcclelland1002** [comment]
`from django.db import connection`
`SQL_COMMAND = f'CREATE TRIGGER audit_table AFTER INSERT OR UPDATE OR DELETE ON... {connection.schema_name}'`
`migrations.RunSQL(SQL_COMMAND)`

**Comment by andyp05** [comment]
thanks for the suggestion. this seems to work.
