### ISSUE TITLE
Test tenant fails if user is required in tenant model

### ISSUE THREAD

**Issue by andyp05** [django-tenants/django-tenants#478]
I have added an owner field to the Tenant model. 

```
class Tenant(TenantMixin):
    paid_until = models.DateTimeField(default=datetime(1999, 1, 1, tzinfo=timezone.utc))
    on_trial = models.BooleanField(default=False)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
```
The program runs fine, but when running tests, the DB creation fails with: 

`sycopg2.errors.NotNullViolation: null value in column "owner_id" violates not-null constraint`

Is there a clean way to:
1. create a user in the public schema.
2. add the tenant record with the user defined.

I can make the owner field null=True and add it later, but I would like to enforce the not null on the field.

Thanks for any ideas.

**Comment by mikicz** [comment]
I believe that's because there's a tenant automatically created for the public schema in tests, which in your DB design would have to be owned by somebody as well. I think you'd have to override the test class to create the public schema tenant with a owner

**Comment by andyp05** [comment]
I will try that. Thanks.
