### ISSUE TITLE
How can i access all tenants (schemas) from one single instance?

### ISSUE THREAD

**Issue by edgebasis** [django-tenants/django-tenants#479]
I know that schemas are designed to separate the data but in some cases you want to search for some data among all schemas. Is this possible?

thanks

**Comment by tomturner** [comment]
@edgebasis No you can't. I do it by loop though each tenant and run the same query however if you got hundreds of tenants that won't work/

**Comment by nikolas310** [comment]
@tomturner can you show demo? How can I get another tenant user from public
