### ISSUE TITLE
How can I use Amazon S3 as storage for media and static content with django-tenants?

### ISSUE THREAD

**Issue by nicksce** [django-tenants/django-tenants#487]
## Use case

For example, I have created 5 tenants in a Django project. I want to use Amazon S3 for storing their static files and media content. The templates will remain on the Django server.

I want to access the tenants' data as below:

https://domain.s3.amazonaws.com/static/tenants[tenant_name/img/icon.svg
https://domain.s3.amazonaws.com/media/tenants/[tenant_name]/images/image.jpg

**Comment by tomturner** [comment]
I use s3 for storage for the media. I use a library called https://github.com/edoburu/django-private-storage. I had to override one part to make sure the files go in to folder of the tenant.

**Comment by nicksce** [comment]
> I use s3 for storage for the media. I use a library called https://github.com/edoburu/django-private-storage. I had to override one part to make sure the files go in to folder of the tenant.

Thanks for your reply.

Can we not use `django-storages`?

**Comment by nicksce** [comment]
> I use s3 for storage for the media. I use a library called https://github.com/edoburu/django-private-storage. I had to override one part to make sure the files go in to folder of the tenant.

Can you please provide more details of the implementation you did?

**Comment by nicksce** [comment]
Made it work after refering to https://github.com/django-tenants/django-tenants/issues/242#issuecomment-511259811

Closing the issue.
