### ISSUE TITLE
Does this play nicely with Django's database routing?

### ISSUE THREAD

**Issue by ajendrex** [django-tenants/django-tenants#489]
Hi,

I'm designing a solution for a project that requires phisically separating data according to its nature: Clients data, Users data and System data. Let's say I will have django's auth tables on default database, and that I will create a couple of django apps; the clients app and the system app, each one having it's models routed to separate databases.

Can I have django-tenants working in this scenario? Does it work out of the box or how hard it would be have it?

Thanks for any insight,
greetings!.

**Comment by tomturner** [comment]
I haven't tried using multiple databases however I can't see why it shouldn't work.

**Comment by ajendrex** [comment]
Thanks @tomturner! In case we go for this solution I will publish the results here 👍
