### ISSUE TITLE
Sub-folder known limitations?

### ISSUE THREAD

**Issue by xyeres** [django-tenants/django-tenants#491]
Hi Tom and team, 

I am fairly new to django-tenants. Reading documentation I noticed the sub-folder feature. I would prefer to implement this in my project however I am hesitant due to the Beta status.

Are there known issues or limitations that I should seriously consider before switching to the sub-folder schema?

Thank you for the time.

**Comment by MathiasKowoll** [comment]
Still now, I did not catch any drawback till now

**Comment by tomturner** [comment]
I personal don't use the sub-folders I use sub-domain. I have only used sub-folders in the example project. However I haven't been told of any bugs.

**Comment by xyeres** [comment]
Good to know, thanks for the reply.
