### ISSUE TITLE
Possible to map "tenant1.saasapp.com" to a customer's/tenant's own domain as "saasapp.customerdomain.com"?

### ISSUE THREAD

**Issue by wimolivier** [django-tenants/django-tenants#492]
Hi everyone,

Is it possible to map "tenant1.saasapp.com" to a customer's/tenant's own domain as "saasapp.customerdomain.com"?
That way the customer is a tenant on the SAAS app, but the customer's users access the app via the customer's own DNS domain name, with a CNAME or something in front of it.

Many thanks,
Wim

**Comment by tomturner** [comment]
Yes it is possible.
However you will have to deal with a few issues.

   - You would need to route that domain to the django app in something
   like NGINX or whatever you use
   - You would need to get a SSL certificate for each domain

The system also allows you to have multiple domain names pointing to the
same tenant so tenant1.saasapp.com and sassapp.customerdomain.com can both
point to the same tenant.

Tom

**Comment by wimolivier** [comment]
Thanks Tom!
I'll give it a bash.

Does that mean I have to add both "tenant1.saasapp.com" and "sassapp.customerdomain.com" as domain names for a tetant in the DB via django-tenants?  How do I do that?

**Comment by tomturner** [comment]
Yes it does add them both to the domain model.  I suggest add them using
Django Admin

**Comment by wimolivier** [comment]
Fantastic, thanks Tom!
