### ISSUE TITLE
Multiple types of tenants

### ISSUE THREAD

**Issue by knivets** [django-tenants/django-tenants#494]
Is it possible to create multiple types of tenants, where each type of tenant has its own `TENANT_APPS` and `TENANT_MODEL` settings. If not how hard would it be to extend this package to implement the support?

**Comment by tomturner** [comment]
This is something already on my list of todo's

**Comment by io-ma** [comment]
I was wondering about the same thing. 
And I thought an approach would be using the Django Sites framework, like explained in the docs:
https://docs.djangoproject.com/en/3.1/ref/contrib/sites/#associating-content-with-a-single-site
But my obstacle is I can't picture clearly  how that would work, would I need more settings files? 
In my particular case, some tenants would require SSO, others mfa auth.

**Comment by tomturner** [comment]
As I need this for my current project I am working on it.
The work is in a branch https://github.com/django-tenants/django-tenants/tree/multi-types
You will find an example project called tenant_multi_types it is very much in development at the moment

**Comment by knivets** [comment]
Awesome! Quick question: is it required for each tenant to have its own `urlconf`?

**Comment by tomturner** [comment]
@knivets Yes however you can set it to the same as one of the other types

**Comment by knivets** [comment]
Got it. Why did you choose to implement it this way rather than via middleware or something?

**Comment by tomturner** [comment]
Changed had to be made to a lot more than url routing. I had to change the migrations to stop db tables getting created if the app wasn't in the installed app. Also there was changes to the admin area. I didn't really have a choice however I feel the solution is quite clean.
