### ISSUE TITLE
Collectstatic_shemas not working properly

### ISSUE THREAD

**Issue by Wisbits** [django-tenants/django-tenants#498]
I am running django 3.1.3 with django-tenants@django-3-1. When I try to collect static files with collectstatic_schemas
I am getting one error that was only documented on SO for django-tenant-schemas.

I am running: < python manage.py collectstatic_schemas --schema=public >
`argparse.ArgumentError: argument --skip-checks: conflicting option string: --skip-checks`

I tried to override the standard command as "fixed_collectstatic", defining the following attribute:
`requires_system_checks = []`

When running this command as <python manage.py fixed_collectstatic --schema=public> django throws the following error:
LookupError: No installed app with label 'staticfiles'.

It all doesn't make any sense for me. Help would be much appreciated.

**Comment by Wisbits** [comment]
Alright, it was a personal mistake. I had copied the django.contrib apps from the django-tenants documentation. Which is lacking the django.contrib.statisfiles app.

**Comment by jbhuff** [comment]
but this issue is still in the code, no?  Can you make a pull request?

**Comment by loctimize** [comment]
I am also having this issue. How did you fix it?

**Comment by jbhuff** [comment]
I created the file f_collectstatic_schemas.py.  It has a fix I found on
other projects.
and now instead of running python manage.py collectstatic_schemas, i call
python manage.py f_collectstatic_schemas.
I have attached the file.
add it to your django tenants library directory.  mine was
/usr/local/lib/python3.8/dist-packages/django_tenants/management/commands/
good luck

**Comment by loctimize** [comment]
Thanks jbhuff! Unfortunately, the attachment has been removed by github. Could you please share it via a repo or link? Many thanks, Daniel

**Comment by diveshkapoor** [comment]
![image](https://user-images.githubusercontent.com/64074782/105338657-d1d43480-5c01-11eb-8e21-48b89e2b4485.png)
![image](https://user-images.githubusercontent.com/64074782/105338724-e3b5d780-5c01-11eb-8185-ef946592a1e1.png)
I have been facing this issue with django 3.1.3, can the owner reopen this thread?

**Comment by jcass77** [comment]
It looks like [--skip-checks](https://docs.djangoproject.com/en/3.1/ref/django-admin/#cmdoption-skip-checks) was added in Django 3.0, though I don't understand why it would introduce the `conflicting option string` error.

I'm not running Django 3.0 yet so may not be able to debug this myself at this stage.

It might be possible to work around this by inserting `requires_system_checks = False` in [collectstatic_schemas.py](https://github.com/django-tenants/django-tenants/blob/6fbf37fd5e042dbbf34ba3928e975ceddd04c942/django_tenants/management/commands/collectstatic_schemas.py#L6) until somebody figures out what is going on.

**Comment by diveshkapoor** [comment]
Hi John

I downgraded from django 3.1.3 to django 3.0 and it worked, some changes in
django syntax in 3.1 may have made it incompatible with django tenants, it
finally worked for me after 3 days of exploring everything

Thanks for your help
Divesh

**Comment by jcass77** [comment]
It looks like Django 3.1.x. contains a conflicting `--skip-checks` in [collectstatic.py](https://github.com/django/django/blob/3.1.3/django/contrib/staticfiles/management/commands/collectstatic.py#L40) and [base.py](https://github.com/django/django/blob/3.1.3/django/core/management/base.py#L293).

It seems like too big of an issue to have gone unnoticed in the Django project, so there might be some nuance to how we are re-purposing `collectstatic` for `collectstatic_schemas` in django-tenrants that Django 3.1.x does not like.

There's been some more work done on this in Django 3.2.x so upgrading to that version could potentially also resolve the issue, though I am unable to confirm myself.

**Comment by agilyol** [comment]
@jcass77 Django 3.2.4 still have same issue

**Comment by artsim** [comment]
> @jcass77 Django 3.2.4 still have same issue

Did you manage to solve this?

Facing the same issue with Django ver 3.2.5

**Comment by chauncy-sue** [comment]
Facing the same issue with Django ver 3.2.5, toooooo

That's hurt!
