### ISSUE TITLE
tenant_context does not set tenant in connection

### ISSUE THREAD

**Issue by NotANormalNerd** [django-tenants/django-tenants#501]
We are currently migration from the abandoned project to this one and stumbled across some weird changes.

https://github.com/django-tenants/django-tenants/commit/83de44af979dbf9b47f68aaa434b91f97d44eef8 removed the tenant_context and basically made it schema_context which are two different approaches to tenant contexts.

Please revert the commit and bring back the functionality or remove tenant_context altogether.

**Comment by tomturner** [comment]
@NotANormalNerd Thanks I reverted the change. Thanks you for pointing this out. I am not releasing a new version for a week or so.

**Comment by NotANormalNerd** [comment]
Thank you for the fast response. :-D
