### ISSUE TITLE
Querying another tenant data inside public tenant

### ISSUE THREAD

**Issue by nikolas310** [django-tenants/django-tenants#507]
querying another tenant data is not working

```
class ClientDetailView(DetailView):
    model = Client

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = None
        with schema_context(self.object.schema_name):
            context['users'] = User.objects.all()
        return context
```

**Comment by nikolas310** [comment]
Have anyone solve this?
```
class ClientDetailView(DetailView):
    model = Client

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = None
        with schema_context(self.object.schema_name):
            context['users'] = User.objects.all()
           --> getting tenant data
        --> getting public data
        return context
```

**Comment by edgebasis** [comment]
from the public schema or any other schema as long as you iterate through the schemas, do this:
mytenant is just an example of filtering if you are searching for a specific tenant. also the exclude is just to avoid the public schema if you have any Users to not show.
```
from django_tenants.utils import schema_context, get_tenant_model, tenant_context

users = []
 for tenant in get_tenant_model().objects.exclude(schema_name='public').filter(name=mytenant):
            with tenant_context(tenant):
                queryset = User.objects.all()
               ## do what ever you want with the data here
                serializer = UserSerializer(queryset, many=True)
              
                users.append(serializer.data)
        return Response(users)
```

**Comment by nikolas310** [comment]
> 
> 
> from the public schema or any other schema as long as you iterate through the schemas, do this:
> mytenant is just an example of filtering if you are searching for a specific tenant. also the exclude is just to avoid the public schema if you have any Users to not show.
> 
> ```
> from django_tenants.utils import schema_context, get_tenant_model, tenant_context
> 
> users = []
>  for tenant in get_tenant_model().objects.exclude(schema_name='public').filter(name=mytenant):
>             with tenant_context(tenant):
>                 queryset = User.objects.all()
>                ## do what ever you want with the data here
>                 serializer = UserSerializer(queryset, many=True)
>               
>                 users.append(serializer.data)
>         return Response(users)
> ```

Not working

**Comment by russell310** [comment]
```
    def get_queryset(self):
        import copy
        with schema_context('tenant1'):
            object_list = copy.copy(Staff.objects.all())
        return object_list
```

**Comment by russell310** [comment]
possible solution:

```
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = None
        import copy
        with schema_context('schema_name'):
            context['users'] = copy.copy(User.objects.all())
        return context
```
