### ISSUE TITLE
How can I make request for a specific tenant schema which is not a tenant extract from subdomain URL?

### ISSUE THREAD

**Issue by KenmogneThimotee** [django-tenants/django-tenants#509]
HOW CAN I MAKE REQUEST FOR A SPECIFIC TENANT SCHEMA WHICH IS NOT A TENANT EXTRACT FROM SUBDOMAIN URL ?

**Comment by tomturner** [comment]
Convert to lowercase.

**Comment by tomturner** [comment]
you need to look at the schema_context and tenant_context

**Comment by KenmogneThimotee** [comment]
OK thank you.
