### ISSUE TITLE
How to get the user object who own the subdomain?

### ISSUE THREAD

**Issue by sbiju** [django-tenants/django-tenants#512]
I was trying to save the stripe api keys to the user who owns the subdomain on subdomain site. How I can get the user object there, looking forward for your help. This is my client model
```
class Client(TenantMixin):
    name = models.CharField(max_length=100)
    paid_until =   ##models.DateField(default=ten_days)
    on_trial = models.BooleanField(default=True)
    created_on = models.DateField(auto_now=True)
    user = models.ForeignKey(User, related_name='clients', on_delete=models.CASCADE, blank=True, null=True)
```

**Comment by tomturner** [comment]
What I would do is passthe client_id over to stripe and have a public url that forwards to the correct tenant
