### ISSUE TITLE
current release 3.21 doesn't properly support multitentant types

### ISSUE THREAD

**Issue by gerald9784** [django-tenants/django-tenants#513]
Some django_tenants.util functions like get_tenant_type_choices() and other functionality where commit after version 3.21 was released.

**Comment by tiagosamaha** [comment]
I'm interested too, but release is not available on Pypi.

**Comment by tomturner** [comment]
I haven't released it yet. I will however I wanted to make sure it works before I release it!!!

**Comment by gerald9784** [comment]
Thanks for the work. I will wait for the next release

**Comment by tiagosamaha** [comment]
@tomturner How can I help test?

**Comment by tomturner** [comment]
If you want to test if you could use the dev version and report any bug.

Thanks
