### ISSUE TITLE
How can I create Custom User when using django-tenants?

### ISSUE THREAD

**Issue by wecoon** [django-tenants/django-tenants#522]
I am moving my app to django-tenants, but I could not find any documentation on custom users. I do not need anything complicated. I want to have separate users for each tenant, no magic here. 

I am using the subfolder domain approach (if that is important in this case)

Before, I was overriding BaseUserManager in CustomUserManager, and AbstractBaseUser, PermissionsMixin in my CustomUserModel.

What should I override when using django-tenants, so my custom user would go through django-tenants workflows?

Thanks!

**Comment by rj76** [comment]
Just put 'django.contrib.auth' in TENANT_APPS setting. I have been using that from scratch.

**Comment by wecoon** [comment]
I'm not really good at development and I hope my lack of knowledge will not hurt anyone, but here are some more details:

I added  'django.contrib.auth' to TENANT_APPS, but still getting the same error:
`django.db.utils.ProgrammingError: relation "users_customuser" does not exist`

My CustomUserModel:
```
...
class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = EmptyEmailToNoneField(_('email address'), unique=True, null=True, blank=True)
    first_name = models.CharField(max_length=64, blank=False)
    last_name = models.CharField(max_length=64, blank=False)
    is_verified = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email
```

and here is my CustomUserManager:
```
class CustomUserManager(BaseUserManager):
    def create_user(self, email, password, **extra_fields):

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user
        
    # def create_superuser(self, email, password, **extra_fields):  
        # I commented this out, I think I wont need it now, but still I'll need to test :)
        # ...
```

**Comment by rj76** [comment]
Try to run `manage.py migrate_schemas`

**Comment by wecoon** [comment]
Sorry, I was not clear enough. I am getting this error when I try to run migrations. I dropped DB, but that did not help. I manage to migrate users app only, but it does not help either.  

Just in case, my APPS:
```
SHARED_APPS = (
    'django_tenants',  # mandatory
    'tenants',  # you must list the app where your tenant model resides in
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

TENANT_APPS = (
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'rest_framework',
    'users',
    'tenant_api',
)
```

**Comment by rj76** [comment]
Did you run `manage.py makemigrations` to create the migrations for your custom user model?

**Comment by wecoon** [comment]
I tried it several different ways. Yes, I tried to makemigrations, but also, I tried to follow the documentation, like this: 
1. python manage.py migrate_schemas --shared
2. python manage.py makemigrations
3. python manage.py migrate_schemas --shared

However, in this case I got some error saying, my users app is not migrated, therefore sticking in 1st step

**Comment by rj76** [comment]
weird, did you set `AUTH_USER_MODEL` to `CustomUser` in the settings?

**Comment by wecoon** [comment]
Yes, I did...

**Comment by rj76** [comment]
well, it does make sense to have tenants (schemas) to migrate to :)

**Comment by wecoon** [comment]
Well, it is not really that flow, I was not able to create public or private tenants, before migrating Client and Domain Modules. Funny thing here what I did:

1. migrated tenants app (Client and Domain modules)
2. created public tenant and private tenant1
3. migrated user app (CustomUserModel)
4. so far so good, what is left is: "admin, sessions. " which I cannot migrate. Getting the same `django.db.utils.ProgrammingError: relation "users_customuser" does not exist`

**Comment by rj76** [comment]
Step 3 ran okay? Is that table in the database somewhere?

**Comment by wecoon** [comment]
Oh, ok. Well everything went fine. Now I see that CustomUser table is only in tenant tables, not the public one. Not sure if that is ok.

**Comment by rj76** [comment]
That depends. If you only want customers for a tenant, or globally. I'd say per tenant and then you're good with these settings.

**Comment by wecoon** [comment]
Well, as I put in the edit, this fixed the issue, but I do not really need it SHARED... that is what I do not like about this solution. Error came from admin, so maybe I should also put 'django.contrib.admin', under TENANT_APPS?

**Comment by rj76** [comment]
I'm not using the admin, but it's commented out in SHARED_APPS in my settings

**Comment by rj76** [comment]
oh, admin is there :-1: but not using it :rofl:

**Comment by wecoon** [comment]
Well, I think I will try to move admin to TENANT_APPS or maybe just leave as is for now. 

Thank you very very much, you basically saved my day! I hope this thread will also be useful for the community.

**Comment by rj76** [comment]
good luck :)

**Comment by tomturner** [comment]
@wecoon If you have finished with the please close the ticket. Thanks

**Comment by tomturner** [comment]
@wecoon Thanks :)  Have a good day

**Comment by anugrahsoft** [comment]
Hi @wecoon,

How did you solve your issue with CustomUser, I have the same problem with admin that cauing this error :

I cloned django-tenants from git, it worked with default auth User,  

but when I added  "accounts" app with custom user (AbstractUser), and define : AUTH_USER_MODEL = 'accounts.User' in settings.py

So basically I left everything as it is, it didn't work and throw me an error

Here's a trace :

```
(venv) rado@znb:~/dev/junky-projects/django-tenants/examples/tenant_tutorial$ python manage.py migrate_schemas --shared
[standard:public] === Starting migration
[standard:public] Operations to perform:
[standard:public]   Apply all migrations: accounts, admin, auth, contenttypes, customers, sessions, tenant_only
[standard:public] Running migrations:
[standard:public]   Applying contenttypes.0001_initial...
[standard:public]  OK
[standard:public]   Applying contenttypes.0002_remove_content_type_name...
[standard:public]  OK
[standard:public]   Applying auth.0001_initial...
[standard:public]  OK
[standard:public]   Applying auth.0002_alter_permission_name_max_length...
[standard:public]  OK
[standard:public]   Applying auth.0003_alter_user_email_max_length...
[standard:public]  OK
[standard:public]   Applying auth.0004_alter_user_username_opts...
[standard:public]  OK
[standard:public]   Applying auth.0005_alter_user_last_login_null...
[standard:public]  OK
[standard:public]   Applying auth.0006_require_contenttypes_0002...
[standard:public]  OK
[standard:public]   Applying auth.0007_alter_validators_add_error_messages...
[standard:public]  OK
[standard:public]   Applying auth.0008_alter_user_username_max_length...
[standard:public]  OK
[standard:public]   Applying auth.0009_alter_user_last_name_max_length...
[standard:public]  OK
[standard:public]   Applying auth.0010_alter_group_name_max_length...
[standard:public]  OK
[standard:public]   Applying auth.0011_update_proxy_permissions...
[standard:public]  OK
[standard:public]   Applying auth.0012_alter_user_first_name_max_length...
[standard:public]  OK
[standard:public]   Applying accounts.0001_initial...
[standard:public]  OK
[standard:public]   Applying admin.0001_initial...
Traceback (most recent call last):
  File "/home/rado/dev/junky-projects/django-tenants/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "User" does not exist
```

and here the setting.py :

```
ROOT_URLCONF = 'tenant_tutorial.urls_tenants'
PUBLIC_SCHEMA_URLCONF = 'tenant_tutorial.urls_public'

# Python dotted path to the WSGI application used by Django's runserver.
WSGI_APPLICATION = 'tenant_tutorial.wsgi.application'

SHARED_APPS = (
    'django_tenants',  # mandatory
    'customers',  # you must list the app where your tenant model resides in

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

TENANT_APPS = (
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.sessions',
    'django.contrib.messages',
    'accounts', 
    'tenant_only',
)

TENANT_MODEL = "customers.Client"  # app.Model

TENANT_DOMAIN_MODEL = "customers.Domain"  # app.Model

TEST_RUNNER = 'django.test.runner.DiscoverRunner'

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

###############
# Auth Config #
###############
AUTH_USER_MODEL = 'accounts.User' #changes the built-in user model to ours
```

Any tips how to overcome this ?

**Comment by oicaroabreu** [comment]
> > Hi @wecoon,
> > How did you solve your issue with CustomUser, I have the same problem with admin that cauing this error :
> > I cloned django-tenants from git, it worked with default auth User,
> > but when I added "accounts" app with custom user (AbstractUser), and define : AUTH_USER_MODEL = 'accounts.User' in settings.py
> > So basically I left everything as it is, it didn't work and throw me an error
> > Here's a trace :
> > ```
> > (venv) rado@znb:~/dev/junky-projects/django-tenants/examples/tenant_tutorial$ python manage.py migrate_schemas --shared
> > [standard:public] === Starting migration
> > [standard:public] Operations to perform:
> > [standard:public]   Apply all migrations: accounts, admin, auth, contenttypes, customers, sessions, tenant_only
> > [standard:public] Running migrations:
> > [standard:public]   Applying contenttypes.0001_initial...
> > [standard:public]  OK
> > [standard:public]   Applying contenttypes.0002_remove_content_type_name...
> > [standard:public]  OK
> > [standard:public]   Applying auth.0001_initial...
> > [standard:public]  OK
> > [standard:public]   Applying auth.0002_alter_permission_name_max_length...
> > [standard:public]  OK
> > [standard:public]   Applying auth.0003_alter_user_email_max_length...
> > [standard:public]  OK
> > [standard:public]   Applying auth.0004_alter_user_username_opts...
> > [standard:public]  OK
> > [standard:public]   Applying auth.0005_alter_user_last_login_null...
> > [standard:public]  OK
> > [standard:public]   Applying auth.0006_require_contenttypes_0002...
> > [standard:public]  OK
> > [standard:public]   Applying auth.0007_alter_validators_add_error_messages...
> > [standard:public]  OK
> > [standard:public]   Applying auth.0008_alter_user_username_max_length...
> > [standard:public]  OK
> > [standard:public]   Applying auth.0009_alter_user_last_name_max_length...
> > [standard:public]  OK
> > [standard:public]   Applying auth.0010_alter_group_name_max_length...
> > [standard:public]  OK
> > [standard:public]   Applying auth.0011_update_proxy_permissions...
> > [standard:public]  OK
> > [standard:public]   Applying auth.0012_alter_user_first_name_max_length...
> > [standard:public]  OK
> > [standard:public]   Applying accounts.0001_initial...
> > [standard:public]  OK
> > [standard:public]   Applying admin.0001_initial...
> > Traceback (most recent call last):
> >   File "/home/rado/dev/junky-projects/django-tenants/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
> >     return self.cursor.execute(sql, params)
> > psycopg2.errors.UndefinedTable: relation "User" does not exist
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and here the setting.py :
> > ```
> > ROOT_URLCONF = 'tenant_tutorial.urls_tenants'
> > PUBLIC_SCHEMA_URLCONF = 'tenant_tutorial.urls_public'
> > 
> > # Python dotted path to the WSGI application used by Django's runserver.
> > WSGI_APPLICATION = 'tenant_tutorial.wsgi.application'
> > 
> > SHARED_APPS = (
> >     'django_tenants',  # mandatory
> >     'customers',  # you must list the app where your tenant model resides in
> > 
> >     'django.contrib.admin',
> >     'django.contrib.auth',
> >     'django.contrib.contenttypes',
> >     'django.contrib.sessions',
> >     'django.contrib.messages',
> >     'django.contrib.staticfiles',
> > )
> > 
> > TENANT_APPS = (
> >     'django.contrib.contenttypes',
> >     'django.contrib.auth',
> >     'django.contrib.admin',
> >     'django.contrib.sessions',
> >     'django.contrib.messages',
> >     'accounts', 
> >     'tenant_only',
> > )
> > 
> > TENANT_MODEL = "customers.Client"  # app.Model
> > 
> > TENANT_DOMAIN_MODEL = "customers.Domain"  # app.Model
> > 
> > TEST_RUNNER = 'django.test.runner.DiscoverRunner'
> > 
> > INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]
> > 
> > ###############
> > # Auth Config #
> > ###############
> > AUTH_USER_MODEL = 'accounts.User' #changes the built-in user model to ours
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any tips how to overcome this ?
> 
> Hi, did you finally solved this? I'm facing the same problem. Thanks!!


I was able to make it work by separating the installed apps
```python
# Application definition

DJANGO_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.staticfiles",
]

BASE_APPS = [
    "django_tenants",
    "organizations",
]

THIRD_PARTY_APPS = [
    "sass_processor",
]

PG_EXTRA_SEARCH_PATHS = []

TENANT_APPS = [
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.admin",
    "django.contrib.auth",
    "finance.perfil",
    "finance.extrato",
    "finance.planejamento",
    "finance.contas",
    "schedule.appointments",
    "schedule.accounts",
    "schedule.treatments",
]

SHARED_APPS = BASE_APPS + DJANGO_APPS + THIRD_PARTY_APPS

INSTALLED_APPS = list(SHARED_APPS) + [
    app for app in TENANT_APPS if app not in SHARED_APPS
]
```

**Comment by alejandroarancibia07** [comment]
Hi, it’s a bit hacky, but you have to put all the apps on shared apps that means al related to users too. Then start migrating one by one, do it use Python manage.py migrate only, doograrions one by one. You need to have the users table created before creating g the rest, and that must be done on the public schema. After a siscrsfull creation on public avena or shared apps, move all your tenant apps to tenant apps and migrate one by one again. Be aware that you will have user model tables on public schema and others on their own schema, but this is not a real problem. Hope this solves your issues, it was a pain for me too. Cheers!!


On Nov 3, 2023, at 18:05, Ícaro Abreu ***@***.***> wrote:

﻿

Hi @wecoon<https://github.com/wecoon>,
How did you solve your issue with CustomUser, I have the same problem with admin that cauing this error :
I cloned django-tenants from git, it worked with default auth User,
but when I added "accounts" app with custom user (AbstractUser), and define : AUTH_USER_MODEL = 'accounts.User' in settings.py
So basically I left everything as it is, it didn't work and throw me an error
Here's a trace :

(venv) ***@***.***:~/dev/junky-projects/django-tenants/examples/tenant_tutorial$ python manage.py migrate_schemas --shared
[standard:public] === Starting migration
[standard:public] Operations to perform:
[standard:public]   Apply all migrations: accounts, admin, auth, contenttypes, customers, sessions, tenant_only
[standard:public] Running migrations:
[standard:public]   Applying contenttypes.0001_initial...
[standard:public]  OK
[standard:public]   Applying contenttypes.0002_remove_content_type_name...
[standard:public]  OK
[standard:public]   Applying auth.0001_initial...
[standard:public]  OK
[standard:public]   Applying auth.0002_alter_permission_name_max_length...
[standard:public]  OK
[standard:public]   Applying auth.0003_alter_user_email_max_length...
[standard:public]  OK
[standard:public]   Applying auth.0004_alter_user_username_opts...
[standard:public]  OK
[standard:public]   Applying auth.0005_alter_user_last_login_null...
[standard:public]  OK
[standard:public]   Applying auth.0006_require_contenttypes_0002...
[standard:public]  OK
[standard:public]   Applying auth.0007_alter_validators_add_error_messages...
[standard:public]  OK
[standard:public]   Applying auth.0008_alter_user_username_max_length...
[standard:public]  OK
[standard:public]   Applying auth.0009_alter_user_last_name_max_length...
[standard:public]  OK
[standard:public]   Applying auth.0010_alter_group_name_max_length...
[standard:public]  OK
[standard:public]   Applying auth.0011_update_proxy_permissions...
[standard:public]  OK
[standard:public]   Applying auth.0012_alter_user_first_name_max_length...
[standard:public]  OK
[standard:public]   Applying accounts.0001_initial...
[standard:public]  OK
[standard:public]   Applying admin.0001_initial...
Traceback (most recent call last):
  File "/home/rado/dev/junky-projects/django-tenants/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "User" does not exist


and here the setting.py :

ROOT_URLCONF = 'tenant_tutorial.urls_tenants'
PUBLIC_SCHEMA_URLCONF = 'tenant_tutorial.urls_public'

# Python dotted path to the WSGI application used by Django's runserver.
WSGI_APPLICATION = 'tenant_tutorial.wsgi.application'

SHARED_APPS = (
    'django_tenants',  # mandatory
    'customers',  # you must list the app where your tenant model resides in

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

TENANT_APPS = (
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.sessions',
    'django.contrib.messages',
    'accounts',
    'tenant_only',
)

TENANT_MODEL = "customers.Client"  # app.Model

TENANT_DOMAIN_MODEL = "customers.Domain"  # app.Model

TEST_RUNNER = 'django.test.runner.DiscoverRunner'

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

###############
# Auth Config #
###############
AUTH_USER_MODEL = 'accounts.User' #changes the built-in user model to ours


Any tips how to overcome this ?

Hi, did you finally solved this? I'm facing the same problem. Thanks!!

I was able to make it work by separating the installed apps

# Application definition

DJANGO_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.staticfiles",
]

BASE_APPS = [
    "django_tenants",
    "organizations",
]

THIRD_PARTY_APPS = [
    "sass_processor",
]

PG_EXTRA_SEARCH_PATHS = []

TENANT_APPS = [
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.admin",
    "django.contrib.auth",
    "finance.perfil",
    "finance.extrato",
    "finance.planejamento",
    "finance.contas",
    "schedule.appointments",
    "schedule.accounts",
    "schedule.treatments",
]

SHARED_APPS = BASE_APPS + DJANGO_APPS + THIRD_PARTY_APPS

INSTALLED_APPS = list(SHARED_APPS) + [
    app for app in TENANT_APPS if app not in SHARED_APPS
]
