### ISSUE TITLE
How to define MEDIA location when using django-tenants?

### ISSUE THREAD

**Issue by wecoon** [django-tenants/django-tenants#523]
I want to have folder for every tenant MEDIA files, but at the moment it is OK for me to have shared static files. 

My settings part for STATIC and MEDIA:
```
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = "/media/"

DEFAULT_FILE_STORAGE = "django_tenants.files.storage.TenantFileSystemStorage"
# MULTITENANT_RELATIVE_MEDIA_ROOT = ""  # (default: create sub-directory for each tenant)
MULTITENANT_RELATIVE_MEDIA_ROOT = "%s" 
```
So, in views I tried to define location as I did before without django-tenants:
`file_location = settings.MEDIA_ROOT + image.svg`

This would work, but it just drops the file to: `'C:\\Users\\PcUser\\Documents\\GitHub\\ProjecName\\media/image.svg'`
No tenant subfolder...

I tried to do it this way: 
`file_location = settings.MULTITENANT_RELATIVE_MEDIA_ROOT + image.svg`
But it would save to:  `'%s/image.svg`

Maybe I should get the schema name from request and just add the folder in views.py? What would be the right way?

Documentation is not really clear on this part, and I cannot put together any concept in my head. Could any one help me out? Thanks!

**Comment by deshrit** [comment]
@wecoon did you fix it?
