### ISSUE TITLE
How to separate Customer account and his customers ?

### ISSUE THREAD

**Issue by dulex123** [django-tenants/django-tenants#524]
I would like my Customer to register himself at example.com, and create multiple tenants like app1.example.com etc. Now I would like to have his customers to register on app1.example.com.

But when I tried this everyone was able to login to everyones tenant?

I'm using django-rest-knox and have set both SHARED_APPS and TENANT_APPS  to have 'knox', 'django.contrib.auth', 'rest_framework', 'django.contrib.sessions'. 

But it doesnt work, s it possible to use public schema for main site and be isolated from others ? 
Do I need multuple User Models for this? CustomerModel and CustomersCustomerModel?

**Comment by jbhuff** [comment]
similar problem. following

**Comment by tomturner** [comment]
You might want to look at #52.
