### ISSUE TITLE
Help, login to django admin page on public schema

### ISSUE THREAD

**Issue by acreations** [django-tenants/django-tenants#528]
I have followed the tutorial but still got issues to login to django admin page

localhost:7999/admin

I still got no tenants found even when I created a tentant to use public schema.

What I want to achieve is that I want to login e.g on domain mydomain.com/admin to administrate all tenants that is subdomain.

mydomain.com/admin to create new tenants etc

Someone that can point me into right direction?

**Comment by tomturner** [comment]
Have you watched the youtube video

**Comment by acreations** [comment]
I got this fixed by using django tenants user repo, thanks anyway
