### ISSUE TITLE
Suggestion to activate github Discussions for this repo

### ISSUE THREAD

**Issue by klausfmh** [django-tenants/django-tenants#534]
github has a new feature called discussion.

I think it might be beneficial to activate this feature.

What do you think?

**Comment by asixela** [comment]
I think this could be a good idea because I would like to contact the developers to find out how to migrate from https://github.com/bernardopires/django-tenant-schemas to this project.

**Comment by tomturner** [comment]
@asixela Thanks that was something I didn't know about.
I have now activated it
