### ISSUE TITLE
Can't Access a tenant via tenant.domain.com after deploying to Heroku

### ISSUE THREAD

**Issue by Algebra7** [django-tenants/django-tenants#538]
All my created tenants are not accessible via tenant.domain.com after deploying to Heroku, The app is working fine locally but in heroku only the public schema is accessible browser cannot access the tenant it keep saying "We can’t connect to the server at tenant.domain.com"

**Comment by tomturner** [comment]
You need wilcard subdomains.  *.domain.com  I think just googling it I found https://blog.heroku.com/add_on_wildcard_domains.   The other way is to use #432  subfolder tenants that was added in v3.2.0 eg www.domain.com/r/tenant_name_here.

**Comment by Algebra7** [comment]
Thanks @tomturner for the helpful information. I see the problem is about a different feature that Heroku offer which i'm not using currently. Thank you so much.
