### ISSUE TITLE
Routes not working for Tenants via sub-folder 

### ISSUE THREAD

**Issue by dacorredor11** [django-tenants/django-tenants#541]
Hello guys. I'm having this awful error when I try to go for a route of any of my tenants via subfolder. The only schema that works with the routes is the public schema. but for the other ones, the routes doesn't appear. I'm trying to launch to production an app but this issue is stoping me. Hope u can help me.

Thanks.

**Comment by Tim-Tam-Git** [comment]
@dacorredor11 
Hi!
Get the same issue nowadays. [Here is](https://github.com/django-tenants/django-tenants/issues/1077#issue-2473662914) details.
I noted the you have closed the issue and wonder if you can handle it. Will be very thankful if you share the solution.
