### ISSUE TITLE
SET LOCAL instead of SET (i.e. SET SESSION) when using PgBouncer in transaction mode

### ISSUE THREAD

**Issue by samuh** [django-tenants/django-tenants#545]
Hi,

I have been using django-tenants successfully for a while now but discovered a rather mysterious issue. Sometimes the connection would not find the tables even though the logs indicated that SET search_path had been successfully run. I was able to track down that most likely the issue originates from SET command with PgBouncer in transaction mode, which is not recommended at least by documentation (https://www.pgbouncer.org/features.html#fnref:2).

I am currently testing to resolve the issue for now by setting PgBouncer to session mode, but I would like to use it in transaction mode in the future. I was able to check that `SET search_path` is only used in a few places in the code, but I am not sure should there be a PR to change the default (not sure what this would mean in the long run) or allow option for setting the `SET LOCAL` instead of `SET SESSION`.

**Comment by samuh** [comment]
The usage of PgBouner and SET has a mention of the caveat at least in Heroku documentation https://devcenter.heroku.com/articles/best-practices-pgbouncer-configuration#pgbouncer-s-connection-pooling-modes

**Comment by tomturner** [comment]
Did you sort the problem out if not please reopen ticket

**Comment by samuh** [comment]
Sorry for delay, I sorted the problem but did not yet try to create a fork with the "SET LOCAL". I was interested on any possible feedback/knowledge about the effect it might have from someone that really understands PostgreSQL. I'll try it soon once I have time and will report.

**Comment by lothemar** [comment]
@tomturner hey, I've hit the same issue & having this option built-in would be a life saver. Could we reopen this & I'll submit a patch?

My approach will be to have `SET LOCAL` as an option for users to opt-in to with the default still being `SET SESSION`. The option would be defined in `settings`.
