### ISSUE TITLE
cron job with tenants

### ISSUE THREAD

**Issue by sapkus** [django-tenants/django-tenants#549]
What would be the best practice to run cron job for tenants ?
I have a simple update task and  it will run at the same time for all the tenants.  
I was looking at django-crontab and started wondering, should it go to shared apps or tenants apps. How do I pass schema?
Any idea or directions where should I look to would be very appreciated.

**Comment by rj76** [comment]
I'm using huey which has a crontab like feature, with that you can handle tenants how you'd like.

**Comment by mcroni** [comment]
Hi @sapkus , i use `tenant-schemas-celery` for background related tasks. And you can take a look at this example code to use various tenants or the `public` tenant
```
@app.task(default_retry_delay=2 * 60, ignore_result=True)
def payroll_shoot_notifications(receivers, company, employees, url):

    uniques = [(employees[key]['payslip_link'], key, employees[key]['password']) for key in employees.keys()]
    results = payroll_threads_html_pdf(uniques, url)

    public = get_tenant_model().objects.get(schema_name='public')
    with tenant_context(public):
        for i in results:
            employee = employees[i['unique']]
            mail.send(i['unique'],  # List of email addresses also accepted
                      'payroll@cxxx.com',
                      template='payroll-processed',  # Could be an EmailTemplate instance or name
                      context={
                          'username': str(employee['full_name']).title(),
                          "email": employee['email'],
                          'activation_link': i['link'],
                      },
                      priority='now',
                      )
```

**Comment by tomturner** [comment]
I think that anwsered that quite well so I am closing the ticket.
