### ISSUE TITLE
Got Import error in multitype tenants

### ISSUE THREAD

**Issue by krishna-bhandari** [django-tenants/django-tenants#551]
i got importerror while adding a field typein Client model
![Screenshot from 2021-03-17 09-46-24](https://user-images.githubusercontent.com/59533492/111413272-0c3fe680-8706-11eb-841d-061f15d5fd12.png)

**Comment by janaki-sasidhar** [comment]
The pip package isnt updated yet. I think tom needs to do that. I faced the same issue
