### ISSUE TITLE
management commands require a running db when PG_EXTRA_SEARCH_PATHS is set.

### ISSUE THREAD

**Issue by dperetti** [django-tenants/django-tenants#553]
Because [the check](https://github.com/django-tenants/django-tenants/blob/25eca1ce28bee5e36bfd6ac19127ab75e14eb304/django_tenants/apps.py#L38) that is done in `DjangoTenantsConfig` (still done in `master` despite refactoring), all management commands require an up and running database when PG_EXTRA_SEARCH_PATHS is set.

This breaks `collectstatic`, etc in CI...

**Comment by adrienrusso** [comment]
I had the same concern as you that I addressed in this PR https://github.com/django-tenants/django-tenants/pull/519

**Comment by adrienrusso** [comment]
I opened a PR for that https://github.com/django-tenants/django-tenants/pull/568. The fix was not included in my previous one.
