### ISSUE TITLE
Django-tenants subfolder support not working for private tenants

### ISSUE THREAD

**Issue by dacorredor11** [django-tenants/django-tenants#563]
Hello! 
I have been trying to use the subfolder support for my application but I always get the same error:

![Captura de Pantalla 2021-04-07 a la(s) 11 00 57 p  m](https://user-images.githubusercontent.com/37881424/113966663-221c6500-97f5-11eb-9cce-b7ef9d427adf.png)

It detects the tenant "la-tratorina" but doesn't find the other routes

The strange thing is that it only applies for the private tenants, but when i use the name of the public schema it works perfectly.

![Captura de Pantalla 2021-04-07 a la(s) 11 00 09 p  m](https://user-images.githubusercontent.com/37881424/113966610-03b66980-97f5-11eb-9781-5df2f0a8d8e3.png)

I already tried the example and it works but for my application it happens the issue described above. I also created a new tenant with the create_tenant command but it didn't work

I would love to find the solution to this error. Is an issue that is stopping me to launch my app in production. 

Thanks in advance!!

**Comment by stevenbrand99** [comment]
the same here, it would be very useful and I would be very grateful if you help us to solve this error.

**Comment by mronoffon** [comment]
is TENANT_SUBFOLDER_PREFIX and PUBLIC_SCHEMA_URLCONF set?

**Comment by tomturner** [comment]
Please try new version if it doesn't work please reopen issue

**Comment by vzgopro1** [comment]
Hello, did you find solution ?
