### ISSUE TITLE
schema_needs_to_be_sync signal not very clear how to implment in docs

### ISSUE THREAD

**Issue by m7salam** [django-tenants/django-tenants#564]
in the docs example mentioned as the following 

```@receiver(schema_needs_to_be_sync, sender=TenantMixin)
def created_user_client_in_background(sender, **kwargs):
    client = kwargs['tenant']
    print ("created_user_client_in_background %s" % client.schema_name)
    from clients.tasks import setup_tenant
    task = setup_tenant.delay(client)
```

this line 

`    from clients.tasks import setup_tenant
`

I don't quite understand where is the setup_tenant task 

and inside the task what kind of method should we  provoke to make the migration happen 

if we want to go through celery task 

if someone can elaborate would be great

thanks

**Comment by tomturner** [comment]
I have a handlers.py

@receiver(schema_needs_to_be_sync, sender=TenantMixin)
def created_user_client_in_background(**kwargs):
    pass


hope this helps reopen issue if you need more help

**Comment by m7salam** [comment]
I was able to solve it by looking further down the code and have to know that u need to use the method create_schema() on the tenant object.

that is what is not explained in the documentation also not in the answer above

 we know how to write the signal its just in the documentation saying a task called setup_tenant which u can't find this task anywhere to see whats inside it as an example of full implementation .
 
 thanks for your answer anyway but I was able to solve it on my own .
 
 have a good day ahead

**Comment by chandraguptab** [comment]
I am calling `create_schema()` in following code but still **not able to migrate the db**. Only the schema is created with a single empty table 'django_migrations'.

```
@receiver(schema_needs_to_be_sync, sender=TenantMixin)
def created_user_client_in_background(sender, **kwargs):
    client = kwargs['tenant']
    print ("created_user_client_in_background %s" % client.schema_name)
   
    client.create_schema()
```

**Comment by Hudeh** [comment]
@m7salam please how did u solve this can u help with the code that sync the migration when using the signal mention above. please i really need this asap thank you sir

**Comment by Hudeh** [comment]
@chandraguptab have you been able to solve this and what was your implementaion thanks

**Comment by chandraguptab** [comment]
> @chandraguptab have you been able to solve this and what was your implementaion thanks

Yes. I did implemented. Here's the snippet of the signal:

@receiver(schema_needs_to_be_sync, sender=TenantMixin)
def created_user_client_in_background(sender, **kwargs):
    client = kwargs['tenant']
    call_migrate_schema_util_task(client_id=client.id)

**Comment by Hudeh** [comment]
assuming your call_migrate_shema_util_task has this func in it tenant.create_schema(check_if_exists=True,verbosity=1) also di you make use of the post_schema_sync too how did you pass the variable to send email on post_schema_sync()

**Comment by chandraguptab** [comment]
> post_schema_sync

Yeah. `call_migrate_shema_util_task` calls `create_schema()`.  I never tested the following code but the variable `client` should contain the client object.

```
@receiver(post_schema_sync, sender=TenantMixin)
def created_user_client(sender, **kwargs):
    client = kwargs['tenant']
    print ('email sent') # send email to client to as tenant is ready to use
```

**Comment by Hudeh** [comment]
hello is it possible to use the two signal together and by setting auto_create_schema = False ?
@receiver(post_schema_sync, sender=TenantMixin)
def created_user_client(sender, **kwargs):
    client = kwargs['tenant']
    print ('email sent') # send email to client to as tenant is ready to use 


@receiver(schema_needs_to_be_sync, sender=TenantMixin)
def created_user_client_in_background(sender, **kwargs):
    client = kwargs["tenant"]
    data = {"client": client.id}

**Comment by royroyee** [comment]
@Hudeh 
Did you solve the issue? Could you share your code sample?

Thanks!
