### ISSUE TITLE
Allow path based tenacy

### ISSUE THREAD

**Issue by Jufik** [django-tenants/django-tenants#567]
Hello there, 

I did use this awesome lib' to get Multitenancy working using a path based pattern rather than domain based pattern.
Thank for the great job.

I had to rewrite:

- Middleware
- Cases
- Reverse Monkey patch for getting the admin working
- Custom Admin site to allow two admin cased: "Common share apps admin" and "Shared apps admin".

Right now this is included in a private repo.
I'm wondering if you would be interested in getting this as a contribution.

Bests, 
Julien Kieffer

**Comment by tomturner** [comment]
This projct allready allows this this is an example of it https://github.com/django-tenants/django-tenants/tree/master/examples/tenant_subfolder_tutorial

**Comment by tomturner** [comment]
If it wasn't in the project I would have said yes
