### ISSUE TITLE
Subfolder and doc root

### ISSUE THREAD

**Issue by mronoffon** [django-tenants/django-tenants#569]
Hello,

Im attempting to use the 'subfolder' feature and am having difficulty accessing the document root of the website, which
is giving me a 404 - 'Unable to find public tenant'.  Any reason why?  Using MULTITENANT_STATICFILES_DIRS does not seem to help

thanks in advance
mr.onoffon

**Comment by tomturner** [comment]
If version 3.3.0 doesn't fix it please reopen ticket

**Comment by diveshkapoor** [comment]
I have tried using django_tenants with version 3.3.0 and am facing the same issue as above, could you please reopen this ticket.

> Hello,
> 
> Im attempting to use the 'subfolder' feature and am having difficulty accessing the document root of the website, which
> is giving me a 404 - 'Unable to find public tenant'. Any reason why? Using MULTITENANT_STATICFILES_DIRS does not seem to help
> 
> thanks in advance
> mr.onoffon
