### ISSUE TITLE
BaseTenantCommand Not very clear in docs

### ISSUE THREAD

**Issue by rayvikram** [django-tenants/django-tenants#572]
Thanks for this amazing project. 
I read https://django-tenants.readthedocs.io/en/latest/use.html#management-commands and tried to implement a command that will list all groups in all tenants. 

As per the docs/my understanding, we need to create a separate command `list_tenant_group` and in `list_group`, we can give COMMAND_NAME=`list_tenant_group` and this command should run for all tenants.
```
#list_tenant_group.py
from django.core.management.base import BaseCommand

class Command(BaseCommand):
    help  = 'List all group'
    
    def handle(self, *args, **options):
        print('FROM list_tenant_group')

```
```

#list_group.py
from django_tenants.management.commands import BaseTenantCommand

class Command(BaseTenantCommand):
    COMMAND_NAME = 'list_tenant_group'
    
    def handle(self, *args, **options):
        print('FROM list_group')

```
After running `python manage.py list_group ` I am only getting - `FROM list_group` which means it is not running the `list_tenant_group` for every tenant. 

Either it's not working or I am not following the proper way.

**Comment by tomturner** [comment]
I do something like this

```
class Command(BaseCommand):

    def handle(self, *args, **options):
        for tenant in get_tenant_modal().objects.all():
            with tenant_context(client):
                self.stdout.write(self.style.WARNING('Processing %s' % tenant.schema_name))
```

**Comment by rayvikram** [comment]
Thanks!
