### ISSUE TITLE
Not available for this type of schema

### ISSUE THREAD

**Issue by hanckmann** [django-tenants/django-tenants#577]
Since my last update of all my packages, the admin site does not work properly anymore.
Almost all Apps in the admin site are grey and show the text "Not available for this type of schema".

The packages (and their versions) which I use are listed below. I highlighted those which might be most relevant.

argon2-cffi==20.1.0
asgiref==3.3.4
boto3==1.17.56
botocore==1.20.56
cffi==1.14.5
concurrent-log-handler==0.9.19
**Django==3.2**
django-clearcache==1.2.1
django-environ==0.4.5
django-hashids==0.4.0
django-impersonate==1.7.3
django-js-asset==1.2.2
django-mptt==0.12.0
django-redis==4.12.1
django-ses==2.0.0
**django-tenants==3.3.0**
**djangorestframework==3.12.4**
djangorestframework-simplejwt==4.6.0
future==0.18.2
gunicorn==20.1.0
hashids==1.3.1
huey==2.3.2
jmespath==0.10.0
numpy==1.20.2
pandas==1.2.4
portalocker==2.3.0
psycopg2==2.8.6
pycparser==2.20
PyJWT==2.0.1
python-dateutil==2.8.1
pytz==2021.1
redis==3.5.3
s3transfer==0.4.2
six==1.15.0
sqlparse==0.4.1
urllib3==1.26.4

Any idea what this  might be?
Do you need more information?

I use a make file to enter commands, so I am very sure that I only run the tenant aware versions of the management commands.

**Comment by RohanGhodke** [comment]
Did you find out the answer?

**Comment by tomturner** [comment]
Are you logging in to the admin from the shared / public url or from a tenant url?

**Comment by RohanGhodke** [comment]
The issue is for both, the shared as well as tenant url, I tried including the tenant apps in shared app also still no effect. Also the migrations are applied just shows not available in django admin

**Comment by tomturner** [comment]
This is working for me so can you send me the the installed apps config and
the shared apps config

**Comment by RohanGhodke** [comment]
My list of shared and tenant apps

SHARED_APPS = (
    'django_tenants',
    'customers',
    'phonenumber_field',
    'accounts.apps.AccountsConfig',
    'api.apps.ApiConfig',
    'masters.apps.MastersConfig',
    'rest_framework',
    'rest_framework.authtoken',
    'django_extensions',

    'django.contrib.contenttypes',

    # everything below here is optional
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.admin',
    'django.contrib.staticfiles',
)

TENANT_APPS = (
    # The following Django contrib apps must be in TENANT_APPS
    'django.contrib.contenttypes',

    # your tenant-specific apps
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'phonenumber_field',
    'accounts.apps.AccountsConfig',
    'api.apps.ApiConfig',
    'masters.apps.MastersConfig',
)

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

**Comment by hanckmann** [comment]
I will also share my installed apps:

    # APPS (MULTI-TENANT)
    # ------------------------------------------------------------------------------
    # https://django-tenant-schemas.readthedocs.io/en/latest/install.html#configure-tenant-and-shared-applications
    SHARED_APPS = (
        'django_tenants',                   # mandatory, should always be before any django app
        'api.client.apps.ClientConfig',     # you must list the app where your tenant model resides in
        # DJANGO_APPS
        'django.contrib.contenttypes',
    )
    TENANT_APPS = (
        'django.contrib.contenttypes',
        # THIRD_PARTY_INIT_APPS
        'clearcache',
        # DJANGO_APPS
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.sessions',
        'django.contrib.messages',
        "django.contrib.staticfiles",
        # THIRD_PARTY_APPS
        'rest_framework',
        'rest_framework_simplejwt.token_blacklist',
        'impersonate',
        'mptt',
        'huey.contrib.djhuey',
        # LOCAL_APPS
        'api.client_profile.apps.ClientProfileConfig',
        'api.accounts.apps.AccountsConfig',
        'api.account_profiles.apps.AccountProfilesConfig',
        'api.clusters.apps.ClustersConfig',
        'api.reports.apps.ReportsConfig',
        'api.user_priorities.apps.UserPrioritiesConfig',
        'api.huey_email.apps.HueyEmailAppConfig',
        'api.toolz.apps.ToolzConfig',
    )
    # https://docs.djangoproject.com/en/dev/ref/settings/#installed-apps
    INSTALLED_APPS = SHARED_APPS + tuple(app for app in TENANT_APPS if app not in SHARED_APPS)
    # https://django-tenant-schemas.readthedocs.io/en/latest/install.html#configure-tenant-and-shared-applications
    TENANT_MODEL = "client.Client"
    TENANT_DOMAIN_MODEL = "client.Domain"


I also added my requirements.txt, as there might be something wrong there as well:

    wheel

    pytz==2021.1  # https://github.com/stub42/pytz

    # https://docs.djangoproject.com/en/dev/topics/auth/passwords/#using-argon2-with-django
    argon2-cffi==20.1.0  # https://github.com/hynek/argon2_cffi

    psycopg2==2.8.6  # https://github.com/psycopg/psycopg2
    redis==3.5.3  # https://github.com/andymccurdy/redis-py
    gunicorn==20.1.0  # https://github.com/benoitc/gunicorn

    # Django
    # ------------------------------------------------------------------------------
    django==3.0.14  # https://www.djangoproject.com/
    #django==3.1.8  # https://www.djangoproject.com/  # UNSUPPORTED DUE TO DRF / DJANGO-TENANTS
    #django==3.2  # https://www.djangoproject.com/     # UNSUPPORTED DUE TO DRF / DJANGO-TENANTS
    django-environ==0.4.5  # https://github.com/joke2k/django-environ
    django-tenants==3.3.0  # https://django-tenants.readthedocs.io/en/latest/install.html

    # Django REST Framework
    # ------------------------------------------------------------------------------
    djangorestframework==3.12.4  # https://github.com/encode/django-rest-framework
    djangorestframework-simplejwt==4.6.0  # https://github.com/SimpleJWT/django-rest-framework-simplejwt
    #django-cors-headers==3.7.0  # https://github.com/adamchainz/django-cors-headers

    # Django Caching and Queues
    # ------------------------------------------------------------------------------
    django-clearcache==1.2.1  # https://github.com/timonweb/django-clearcache
    django-redis==4.12.1  # https://github.com/jazzband/django-redis
    huey==2.3.2  # https://huey.readthedocs.io/en/latest/index.html

    # Django App (accounts)
    # ------------------------------------------------------------------------------
    django-hashids==0.4.0  # https://github.com/ericls/django-hashids
    django-impersonate==1.7.3  # https://code.netlandish.com/~petersanchez/django-impersonate/

    # Specials
    # ------------------------------------------------------------------------------
    django-mptt==0.12.0  # https://github.com/django-mptt/django-mptt
                         # DJANGO-MPTT IS CURRENTLY UNMAINTAINED

    # E-mail
    # ------------------------------------------------------------------------------
    django-ses==2.0.0

    # Calculations etc.
    # ------------------------------------------------------------------------------
    pandas==1.2.4  # https://pandas.pydata.org/

    # Debugging
    # ------------------------------------------------------------------------------
    Werkzeug==1.0.1 # https://github.com/pallets/werkzeug
    ipdb==0.13.7  # https://github.com/gotcha/ipdb
    django-debug-toolbar==3.2.1  # https://github.com/jazzband/django-debug-toolbar

    # Testing
    # ------------------------------------------------------------------------------
    mypy==0.812  # https://github.com/python/mypy
    pytest==6.2.4  # https://github.com/pytest-dev/pytest
    pytest-sugar==0.9.4  # https://github.com/Frozenball/pytest-sugar
    pytest-django==4.2.0  # https://github.com/pytest-dev/pytest-django
    factory-boy==3.2.0  # https://github.com/FactoryBoy/factory_boy

    # Documentation
    # ------------------------------------------------------------------------------
    sphinx==3.5.4  # https://github.com/sphinx-doc/sphinx
    sphinx-autobuild==2021.3.14 # https://github.com/GaretJax/sphinx-autobuild

    # Code quality
    # ------------------------------------------------------------------------------
    coverage==5.5  # https://github.com/nedbat/coveragepy
    django-coverage-plugin==1.8.0  # https://github.com/nedbat/django_coverage_plugin

    # Upgrades
    # ------------------------------------------------------------------------------
    pip-upgrader==1.4.15  # https://github.com/simion/pip-upgrader


Finally, I will add a screenshot of how the admin panel looks at my end:

![not-available-error](https://user-images.githubusercontent.com/925657/117541675-32eb1100-b015-11eb-9c8e-9dab03ea52d0.png)

**Comment by ronbeltran** [comment]
I had experienced the same issue. Somehow after the django-tenants upgrade my TENANT_APPS are disabled or "Not available for this type of schema". I downgraded to my previous working version. But hopefully the issue should eventually be resolved.

    django-tenants==3.2.1 => django-tenants==3.3.0

**Comment by beckedorf** [comment]
In my case removing `.apps.ClientProfileConfig` in the settings solved the problem (and I didn't have a prefix like `api.`, but this might not be relevant).

**Comment by ronbeltran** [comment]
@beckedorf Thanks for the tip! It works on my end. So I wanted the tenant model to be available at the public schema admin page so that superusers can view them.

    'shop.tenants.apps.TenantsConfig',  # tenant model

The above shows the app in admin as "Not available for global schema".

As per your suggestion, it now shows as available in the public schema admin page.

    'shop.tenants',  # tenant model

**Comment by hanckmann** [comment]
Actually, I had to remove the .apps.****Config from all my models.
My tests are still oke.

Why is that difference there?
The Django docs tell us that both options should work: https://docs.djangoproject.com/en/3.2/ref/applications/

Is this a bug in django-tennants?

**Comment by hanckmann** [comment]
Also, when not referencing the .apps.****Config explicitely.
Make sure to reference it in the __init__.py:

    default_app_config = 'my_app.apps.MyAppConfig'

Although... I do find this a bit cumbersom. Also it is not very nice with respect to reusability of the apps (as the top-level module needs to be named as well in the __init__.py).

Calling the `shop.tenants.apps.TenantsConfig` is much more elegant from my point of view.

**Comment by iamunadike** [comment]
This error occurs because django_tenants does not know how to read apps referenced like so:

`app_name.apps.AppNameConfig`
to fix this , simply  use the name of your app;
ie replace any **`app_name.apps.AppConfig`** with just **`app_name`** in either TENANT_APPS or SHARED_APPS or both
Closed

**Comment by marcsabat** [comment]
> This error occurs because django_tenants does not know how to read apps referenced like so:
> 
> `app_name.apps.AppNameConfig`
> to fix this , simply use the name of your app;
> ie replace any **`app_name.apps.AppConfig`** with just **`app_name`** in either TENANT_APPS or SHARED_APPS or both
> Closed

While replacing the apps references to just "app_name" works it does not initialize the app configuration properly.

I have the following code in my apps.py:
`from django.apps import AppConfig
from django.core import serializers

class AppConfig(AppConfig):
    name = 'app'

    def ready(self):
        serializers.BUILTIN_SERIALIZERS.setdefault('fastgeojson', 'app.serializers.fastgeojson')`

Upon changing the apps references to just "app_name" the "ready" function is not called.

**Comment by sim1234** [comment]
I think that the offending change is this: https://github.com/django-tenants/django-tenants/commit/179e1a88499450fbfa5a4a77c0fcfa76cf0417da

**Comment by hanckmann** [comment]
I guess this item can be closed (see previous fix).
