### ISSUE TITLE
Show the main page in the django multi-tenant

### ISSUE THREAD

**Issue by gpxlqa** [django-tenants/django-tenants#578]
I am studing the djanto multi-tenant package.

When i try to access the main page (landing page) at http://127.0.0.1:8000/, I got the following message:

```
Page not found (404)
Request Method: GET
Request URL:    http://127.0.0.1:8000/
Raised by:  core.views.home
No tenant for hostname "127.0.0.1"

You're seeing this error because you have DEBUG = True in your Django settings file. 
Change that to False, and Django will display a standard 404 page.
```

How do I get the landing page (main page) to show correctly?

URL FILE

```
from core.views import home

urlpatterns = [
     path('admin/', admin.site.urls),
     path('', home, name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```

THE VIEW OF LANDINGPAGE
```
from django.shortcuts import render

    def home(request):
        return render(request, 'core/index.html')
```

PARTIAL SETTINGS FILES

```
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

SHARED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_tenants',
    'customer',
    'core', //landing page


]


TENANT_APPS = [
    # The following Django contrib apps must be in TENANT_APPS
    'django.contrib.contenttypes',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',

    # your tenant-specific apps
    'myclientapp',


]

INSTALLED_APPS = list(set(SHARED_APPS + TENANT_APPS))
```

Thank you very much!

**Comment by tomturner** [comment]
You can’t use 127.0.0.1 as it not a domain name. What the YouTube video on
it and I example it in there

**Comment by gpxlqa** [comment]
Hi, thank you for your contact.

This address is the main server of the Django... What I need is when someone access this domain, open the landing page, not a tenant page. 

![image](https://user-images.githubusercontent.com/6579591/115936805-99482f00-a46c-11eb-8cf7-1c863e86754b.png)

How I do to open a landing page, not a tenant page, with a tenant url? I am learning to use the package and I can´t understand in your video.

**Comment by tomturner** [comment]
There a setting to allow you to put a different url file for the
public domain. If you look at the help it will tell you there

**Comment by mcroni** [comment]
@gannetson it doesn't matter the address of the server, you have to setup `PUBLIC_SCHEMA_URLCONF = 'main_app.urls'` this will serve as the default `urls` mapping the project. Watch the video and alter your `hosts` file and you can then be able to access the `127.0.0.1:8000` with an alias like `test.local:8000`.

**Comment by Khnaz35** [comment]
Seems you guys were mentioning some youtube video but can't find the url to it.
Also what if the URL is fixed not multi domains/subdomains ? I am pickingup the identifier from the header.
