### ISSUE TITLE
(django-tenants) NEWBIE Questions: Please Answer... _/\_

### ISSUE THREAD

**Issue by naveens800** [django-tenants/django-tenants#588]
1.In Application code , how can i **query** model which is in TENANT_APPS ?

2.How can i access django admin site for tenants? I faced an error " _DoesNotExist at /admin/login/ (Site matching query does not exist.)_ ", even I added django.contrib.admin added to **TENANT_APPS** ... (Any insights would be helpful)

3. Can i have an app with foreign key relationships in **public** schema with an app or apps in **tenant** schema and **vice-versa**??

Thank you. _/\_

**Comment by mronoffon** [comment]
1) review the 'examples' section and focus on the 'tenent_context'.   Inside this context you'll be able to use the 'standard' django queries

2) in settings.py, do you have 'django.contrib.admin' listed in the 'TENANT_APP'?

3) yes, you can but are you sure you want this?

**Comment by naveens800** [comment]
>     1. review the 'examples' section and focus on the 'tenent_context'.   Inside this context you'll be able to use the 'standard' django queries
> 
>     2. in settings.py, do you have 'django.contrib.admin' listed in the 'TENANT_APP'?
> 
>     3. yes, you can but are you sure you want this?

1. I think you're telling, to resolve host from request and thereby schema , and use schema_context from utls and perform query on the respective schema. am I correct??
2. yes, i already added the django.contrib.admin in TENANT_APPS.
3. OK

**Comment by naveens800** [comment]
And one thing , If the form class, has to call one or more functions which are written in different files and those files performs ORM queries, how can i resolve schema there to successfully execute this queries, because at this time I have no access to request parameter...

**Comment by mronoffon** [comment]
can you provide code snippets of the code where you don't have access to 'request'?

**Comment by naveens800** [comment]
I found my mistake...
Thank you @mronoffon for arguing with me :)
I'm closing this issue
