### ISSUE TITLE
Any way to have a fixed login page ?

### ISSUE THREAD

**Issue by bouhaddiamine** [django-tenants/django-tenants#591]
Hi Guys,

i'm looking for a solution to have one login page

**Comment by tomturner** [comment]
[django tenant users](https://github.com/Corvia/django-tenant-users) project may be what you are looking for

**Comment by bouhaddiamine** [comment]
it's a must to use django tenant user ? please i need your help 
i have installed django_rest  and django-tenants   i try just to get the login token  but the middleware stop me each time

**Comment by bouhaddiamine** [comment]
@tomturner   those are my urls 
    ```
path('api-auth/', include('rest_framework.urls')),
    path('api/rest-auth/', include('rest_auth.urls')),
```

to get token    normally i send a post request to  'http://localhost/:5555/api/rest-auth/login/   

but  now i'm getting an error message  :  no such a tenant localhost
