### ISSUE TITLE
User Specific schema for better seperation of data?

### ISSUE THREAD

**Issue by saileshkush95** [django-tenants/django-tenants#593]
I think we can extend this project one step further. 

If we create scheme on the basis of username,  this will help to maintain multi tenancy.  With just single domain.

**Comment by hanckmann** [comment]
I believe you are looking for something as described in the documentation, here:

https://django-tenant-schemas.readthedocs.io/en/latest/advanced_usage.html#custom-tenant-strategies-custom-middleware-support

**Comment by tomturner** [comment]
This doesn't need to go into this project you could write this on top easily.
