### ISSUE TITLE
Question: Tenant-aware cache_page()

### ISSUE THREAD

**Issue by johnunar** [django-tenants/django-tenants#599]
It seems that when we use the `cache_page()` decorator, it defaults to the public schema. Is there a way to make it tenant-aware? We have the `KEY_FUNCTION` and `REVERSE_KEY_FUNCTION` set.

Thank you.

**Comment by theognis1002** [comment]
[cache_page](https://docs.djangoproject.com/en/4.1/topics/cache/#django.views.decorators.cache.cache_page)
pass in the key_prefix kwarg to the decorator with a lambda function or something that grabs the current schema name via a local thread

**Comment by johnunar** [comment]
Yes, that works.
