### ISSUE TITLE
User sign-ups are extremely slow

### ISSUE THREAD

**Issue by danisaza** [django-tenants/django-tenants#617]
Hi all 👋🏽

I'm wondering whether `django-tenants` is a good fit for my use-case because I'm seeing slowdowns when new users create accounts in my application.

In particular, when a user clicks a "confirm email" link that I send to them, a new Tenant and Domain are created for them, and migrations are automatically run.

Those migrations are taking a while, and - as a result - the "you've confirmed your email" page takes about 30sec to be displayed to the user.

I'm not _so_ concerned about the slowness of the confirmation page - since I assume I could create the new tenant with a Celery task, for example.

However, I _**am**_ worried that the whole database is unavailable for use while migrations run. (i.e. I'm worried that other Tenants experience downtime while a new Tenant's migrations are applied)

Is that the case?

If so, is there some kind of workaround?

------

For context, my application is a micro-saas that I'm hoping will have a large number of customers (i.e. Tenants), and I want them to be able to self-serve during onboarding -- without causing any kind of downtime for other users.

**Comment by mcroni** [comment]
One of the options you can use it to use clones, so its like you have a preset(template) of a schema that you can clone from

**Comment by tomturner** [comment]
@mcroni reply is what I would recommend
