### ISSUE TITLE
AttributeError: 'Client' object has no attribute 'tenant_type'

### ISSUE THREAD

**Issue by Hudeh** [django-tenants/django-tenants#623]
hello, 
using the django_tenant_multi_type i get this error when trying to create superuser after selecting the domain to create superuser for
  File "C:\working_projects\django-tenants\examples\tenant_multi_types\..\..\django_tenants\routers.py", line 45, in allow_migrate
    installed_apps = tenant_types[connection.tenant.tenant_type]['APPS']
AttributeError: 'Client' object has no attribute 'tenant_type'

**Comment by Hudeh** [comment]
solved by going to the django-router.py and change 
installed_apps = tenant_types[connection.tenant.tenant_type]['APPS'] to 
installed_apps = tenant_types[connection.tenant.type]['APPS']

**Comment by samuel1992** [comment]
Hey. I'm having this issue to run the migrations. Where is this file django-routers you have mentioned? @Hudeh ... I'm not seeing it in the documentation =/

**Comment by MusicMack** [comment]
check under django-tenant package you will see  django-router.py, but no need for that change all you need to do is to make sure your client model has this field tenant_type of charfield and set the settings.py HAS_MULTI_TYPE_TENANTS = True
MULTI_TYPE_DATABASE_FIELD = 'tenant_type'

**Comment by MusicMack** [comment]
@samuel1992 am using @MusicMack to reply you which is @Hudeh

**Comment by samuel1992** [comment]
Ahhh, great! Thank you so much for that.

**Comment by MusicMack** [comment]
you welcome sir
