### ISSUE TITLE
Can i manage tenants apps from public schema?

### ISSUE THREAD

**Issue by ranchoteca** [django-tenants/django-tenants#641]
I need to manage each tenant apps and access its data.

In the main tom's example in youtube channel, he creates two apps.

**1. sweet_shared
2. sweet_tenant**

But sweet tenant cannot be accessed from global schema.

There is a way to do this? ​

I'm using **django admin panel** and **tom's example**

Thanks

**Comment by gerald9784** [comment]
Yes you can, in the documentation under utils https://django-tenants.readthedocs.io/en/latest/use.html
There is schema-context and tenant-context. These can enable you to run tenant specific code inside the admin app

**Comment by ranchoteca** [comment]
Got it!

Thanks Gerald
