### ISSUE TITLE
Irregularities between tenant postgres tables in public schema

### ISSUE THREAD

**Issue by ranchoteca** [django-tenants/django-tenants#646]
Hi I'm facing a situation with `customer_client` and `customer_domain` tables in public schema.

if i want to create a new tenant from terminal all is right while im using this command:

`python manage.py create_tenant`

Through above command im able to create schema_name, name and others fields of customer_client table also domain from customer_domain table, maintaining the relationship between customer_client and customer_domain.

But when im logging to django admin panel(public schema), it appears as follows:

<img width="702" alt="Captura de Pantalla 2021-08-09 a la(s) 20 46 52" src="https://user-images.githubusercontent.com/88474129/128804792-dcc9aa04-515d-4295-8cbc-b6cd57052b8e.png">

And later when i try to access customer app(Clients), it shows this:
<img width="701" alt="Captura de Pantalla 2021-08-09 a la(s) 20 48 36" src="https://user-images.githubusercontent.com/88474129/128804857-7ce479c5-3570-43bd-aa36-8868bd85622c.png">

 In the image before you can see that domain input does not appear, and it results that after give clic on save button, the customer_client data is filled but not the customer_domain data, so the relationship is not maintaining between the tables, however when you type one of the tenants url in the browser, all is working despite that no `customer_domain` data is saving in the table.

You can see the lack of some relations between the rows in the next images:

<img width="1087" alt="Captura de Pantalla 2021-08-09 a la(s) 20 45 09" src="https://user-images.githubusercontent.com/88474129/128805286-5df5f1c1-6229-4680-91cb-cb8d95a2c0c0.png">

<img width="890" alt="Captura de Pantalla 2021-08-09 a la(s) 20 45 51" src="https://user-images.githubusercontent.com/88474129/128805301-9fd7c9d2-b83f-423d-be36-0756e0bf6a13.png">

My model.py is:

<img width="649" alt="Captura de Pantalla 2021-08-09 a la(s) 20 51 41" src="https://user-images.githubusercontent.com/88474129/128805392-87bdaf3b-f2b0-403d-8f03-ddd10446241b.png">

And my admin.py is:

<img width="514" alt="Captura de Pantalla 2021-08-09 a la(s) 20 52 22" src="https://user-images.githubusercontent.com/88474129/128805426-dcc2e293-674b-4198-840c-26138b88c81f.png">

Im following the official documentation: [Django tenants](https://django-tenants.readthedocs.io/en/latest/install.html#basic-settings) 

So is it important maintain the relation between customer_client and customer_domain or the django tenants project can work without this relationship ? At least, that is what it seems

**Comment by itzomen** [comment]
Not sure what you did wrong but you can take a look at this video tutorial
https://youtu.be/QU70PbJuAUo

**Comment by tomturner** [comment]
Please see the main video 

https://youtu.be/TWF7okf5Xoo

**Comment by ranchoteca** [comment]
Got it.
Thanks
