### ISSUE TITLE
multi types tenants bug

### ISSUE THREAD

**Issue by freecnpro** [django-tenants/django-tenants#649]
https://github.com/django-tenants/django-tenants/blob/f9bf94a071f6c4a83fc340186fafec80e7131e15/django_tenants/routers.py#L45

Fix:
`tenant_type = connection.tenant.get_tenant_type()`
`installed_apps = tenant_types[tenant_type]['APPS']`

**Comment by tomturner** [comment]
It does look like a bug I will review and patch if required

**Comment by freecnpro** [comment]
> It does look like a bug I will review and patch if required

It's not working when pass a tenant to tenant_context or schema_name to schema_context.
