### ISSUE TITLE
django-tenants with nginx x-accel-redirects

### ISSUE THREAD

**Issue by hanckmann** [django-tenants/django-tenants#650]
I am trying to implement secured downloads for my tenants.

The following links are/might be relevant:

- https://djangosnippets.org/snippets/491/
- https://wellfire.co/learn/nginx-django-x-accel-redirects/
- https://www.digitalocean.com/community/questions/nginx-rule-for-wildcard-url
- https://django-tenants.readthedocs.io/en/latest/files.html#configuring-media-file-storage

I cannot claim to fully understand the nginx x-accel-redirects and their security implications. This is something I will dive deeper into later. First I need to understand how to get this to work with django-tenats.

The references discuss that a `/protected/` folder (with whatever name) is used to store the files.
I assume that this folder must be present in the media folder of all tenants.
Also, how do I setup nginx such that this folder is found in each tenant's media subfolder.

Can somebody provide any pointers, examples, etc to get this to work and such that I can understand this better?

**Comment by tomturner** [comment]
I use https://github.com/edoburu/django-private-storage for my private storage.

**Comment by hanckmann** [comment]
> I use https://github.com/edoburu/django-private-storage for my private storage.

And this works well together with django-tenants ?

**Comment by tomturner** [comment]
I wouldn't recommend it if it didn't work with DT

**Comment by hanckmann** [comment]
A little unrelated to python, but could you share how I need to setup the media part in the nginx config?
It is something I cannot get my head around.

**Comment by hanckmann** [comment]
Oke, I figured it out... it was a settings-issue that was holding me back.
