### ISSUE TITLE
Problem in token generation with django rest framework.

### ISSUE THREAD

**Issue by riverlearning** [django-tenants/django-tenants#654]
My django project is working properly with multi tenant architecture. I have implemented rest framework but it is giving me an error for token authentication. I tried multiple ways for generating token (admin panel, signals , custom token class, djoser package) but I get the same error(below).

IntegrityError at /api/token/login
insert or update on table "authtoken_token" violates foreign key constraint "authtoken_token_user_id_35299eff_fk_accounts_customuser_id"
DETAIL:  Key (user_id)=(3) is not present in table "accounts_customuser".

I think this is because auth token table is created in public schema and users are in seperate schemas.

My settings file -
SHARED_APPS = [
    'django_tenants',
    'accounts.apps.AccountsConfig',
    'customer',
    'api.apps.ApiConfig',            #project containing rest api
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',  
    'crispy_forms',

    'rest_framework', 
    'rest_framework.authtoken',
    'djoser',
]

TENANT_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'accounts.apps.AccountsConfig',
    '
    'api.apps.ApiConfig',     #project containing rest api 
    
    'rest_framework', 
    'rest_framework.authtoken',
    'djoser',
]

INSTALLED_APPS = list(set(SHARED_APPS + TENANT_APPS))

**Comment by itzomen** [comment]
The problem is you are trying to generate a token for a user from the tenant schema and that user isn't saved on the public schema.

What you can do is to handle authentication only on the public schema

**Comment by riverlearning** [comment]
My user authentication is seperate for each tenant. For eg for subdomain  't1.example.com' i have different login page and for subdomain 't2.example.com' i have different login.

**Comment by itzomen** [comment]
Oh I see, consider using django-tenant-user

**Comment by riverlearning** [comment]
Also my django app user the default authentication system provided by django. When i add rest framework login/logout methods they are overriding django default authentication. Any idea on how to keep both session authentication(used by django) and token authentication(used by django rest) seperate.

**Comment by mcquadenc** [comment]
> Also my django app user the default authentication system provided by django. When i add rest framework login/logout methods they are overriding django default authentication. Any idea on how to keep both session authentication(used by django) and token authentication(used by django rest) seperate:

@riverlearning You can use SessionAuthtentication:
```
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ]
}

```


The documentation explains than it uses Django default backend authentication:

> This authentication scheme uses Django's default session backend for authentication

I think DRF do not override django default authentication, but you should enable it.

**Comment by riverlearning** [comment]
Thank you! But i was able to do it with 'rest_framework.authentication.TokenAuthentication'.
