### ISSUE TITLE
Permissions is creating foreign key every time tenant is created

### ISSUE THREAD

**Issue by robertwt7** [django-tenants/django-tenants#661]
Hey guys,

is this actually expected?

Our `auth_permission` and `auth_group_permissions` become very bloated in this way. 

Apologies for the newbie question though I'm still learning this framework.

Thanks!

![image](https://user-images.githubusercontent.com/15647967/132693925-a5ec3bfa-a7ab-4cd6-9696-0112dbf8ef51.png)

**Comment by tomturner** [comment]
yes if you put auth in the shared apps
