### ISSUE TITLE
Postgres backend introspection seems to be out of date

### ISSUE THREAD

**Issue by ZipBrandon** [django-tenants/django-tenants#663]
I am trying to introspect tables in my schema but I am met with an error.  Comparing the latest postgres introspection in Django against circa the time when this file was last committed to django-tenants one can see the deviation.

Latest:
https://github.com/django/django/blob/main/django/db/backends/postgresql/introspection.py

~3 years ago.
https://github.com/django/django/blob/f3a98224e6dd5f8846008512f281e452dc3b1909/django/db/backends/postgresql/introspection.py

Executing
```py
cursor = connection.cursor()
descr = connection.introspection.get_table_description(cursor, table_name)
```
produces the error
```py
  File "/usr/local/lib/python3.8/site-packages/django_tenants/postgresql_backend/introspection.py", line 49, in <listcomp>
    return [FieldInfo(*((force_text(line[0]),) + line[1:6] +
TypeError: __new__() missing 1 required positional argument: 'collation'
```

**Comment by adrienrusso** [comment]
@ZipBrandon I have opened a PR, if you can add a 👍  it will be appreciated.
