### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by macumhail** [django-tenants/django-tenants#680]
When I ran pipenv install django-tenants I received the following error:
File "/Users/mainuser/anaconda/lib/python3.6/site-packages/OpenSSL/rand.py", line 213, in <module>
    _lib.ERR_load_RAND_strings()
AttributeError: module 'lib' has no attribute 'ERR_load_RAND_strings'

Any ideas about how to fix this?

**Comment by tomturner** [comment]
More info need like django version etc

**Comment by macumhail** [comment]
Django version is 3.1.13, python is 3.9.2.

**Comment by macumhail** [comment]
I have a feeling this problem is related to some unknown change that has happened to the virtual environment. I had the same problem attempting to install another package as well.

**Comment by tomturner** [comment]
I would say this isn't a problem with DT and more the way you have got your virtual environment setup.
