### ISSUE TITLE
schema models not updated after a field is changed

### ISSUE THREAD

**Issue by iamunadike** [django-tenants/django-tenants#685]
Hello Tom and all,
I personally noticed that say i have a model A which is in a tenant app say <core>
before:
class A(models.Model):
    x = models.IntegerField()
already migrated and in database

after:
I then modified same model to 
class A(models.Model):
   h = models.CharField(max_length=100)

I run the commands
python3 manage.py makemigrations --fake
python3 manage.py migrate-schemas
it runs perfectly
but the tables are not changed in the database schema they live in , assuming core app is a tenant , 
Please save us stress and help with commands that directly deals with such situations incase a field is changed without having to remove all migrations files , replant it and start getting confused with the rollercoaster of tenants and schemas not being in sync with the changes

**Comment by tomturner** [comment]
Very strange as I haven't had a problem with this. might be worth seeing your settings file

**Comment by iamunadike** [comment]
# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
TENANT_MODEL = 'tenants.Client' #tenant app Model
TENANT_DOMAIN_MODEL = 'tenants.Domain' #tenant app Domain



#MAIN_HOST_NAME = 'apps.local'
# Application definition

TENANT_APPS = [
    # The following Django contrib apps must be in TENANT_APPS
    'django.contrib.contenttypes',

    #my_apps
    'core',
    'accounts',

    #third_party_apps
    'django_filters',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
]


SHARED_APPS = [
    'django_tenants',
    'tenants',
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',

    #for admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',


    'accounts',
    #third_party_apps

]


INSTALLED_APPS = SHARED_APPS + [app for app in TENANT_APPS if app not in SHARED_APPS]

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

**Comment by iamunadike** [comment]
also in this case, the field h=models.Charfield(max_length=100, unique=True) is unique
