### ISSUE TITLE
Schema name

### ISSUE THREAD

**Issue by JupiterThreads** [django-tenants/django-tenants#688]
When I create a schema, I have noticed that it does not accept non `[a-z][0-9_`  characters, but when you look at the [PostgreSQL Schema Create docs](https://www.postgresql.org/docs/13/sql-createschema.html) there is no reason why it shouldn't. In fact I created schema manually with the name `my-test-schema_933333` and I had no problem. 

Are you able to look into this? Thanks

**Comment by tomturner** [comment]
@atodorov Is this todo with #387

**Comment by productdev-catalyst** [comment]
> @atodorov Is this todo with #387

I'm not sure it is because the current regex for validating scheme names, `SQL_IDENTIFIER_RE = re.compile(r'^[_a-zA-Z0-9]{1,63}$')`  doesn't allow hypens yet postgres does. I came across this when sending a valid tenant slug in django-tenant-users `dunder-mifflin` to create a tenant. Django-tenant-users uses the tenant slug for part of the schema name.

**Comment by JupiterThreads** [comment]
> @atodorov Is this todo with #387

I'm not sure it is because the current regex for validating scheme names, `SQL_IDENTIFIER_RE = re.compile(r'^[_a-zA-Z0-9]{1,63}$')` , doesn't allow hypens yet postgres does. I came across this when sending a valid tenant slug in django-tenant-users `dunder-mifflin` to create a tenant. Django-tenant-users uses the tenant slug for part of the schema name.

**Comment by atodorov** [comment]
> @atodorov Is this todo with #387

No b/c 387 is just refactoring without changing the regular expressions or the underlying behavior. 

The regex has been updated in #307 but it never allowed a hyphen to be used. That's how it's been from the start.

**Comment by tomturner** [comment]
@atodorov Do you think we should allow for hyphen?

**Comment by atodorov** [comment]
> @atodorov Do you think we should allow for hyphen?

If it doesn't break anything then why not.

**Comment by tomturner** [comment]
👍

**Comment by Dresdn** [comment]
The [lexical docs](https://www.postgresql.org/docs/13/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS) (while is the v13, same constraints go back to at least v9) call out what can and can't be done, and do make a note about quoted identifiers. Nice thing is that the schema is [already being quoted](https://github.com/django-tenants/django-tenants/blob/master/django_tenants/models.py#L197) by the project.
