### ISSUE TITLE
"tenants_client" does not exist when I run migrate schemas in django 3 , 

### ISSUE THREAD

**Issue by iamunadike** [django-tenants/django-tenants#695]
```
django.db.utils.ProgrammingError: relation "tenants_client" does not exist
LINE 1: SELECT "tenants_client"."schema_name" FROM "tenants_client
```
I get the above with migrate_schemas :
python3 manage.py migrate_schemas

**Comment by esitarski** [comment]
I have the same problem.

```
> python3 manage.py migrate_schemas --shared
[standard:public] === Starting migration
[standard:public] Operations to perform:
[standard:public]   Apply all migrations: admin, auth, contenttypes, core, sessions, sites
[standard:public] Running migrations:
[standard:public]   No migrations to apply.
```
```
> python3 manage.py migrate_schemas --tenant
  ...
django.db.utils.ProgrammingError: relation "customers_client" does not exist
LINE 1: SELECT "customers_client"."schema_name" FROM "customers_clie...
```
Unlike the previous post, my public schema is in "customers", not "tenants", however, I get an equivalent error.

**Comment by esitarski** [comment]
I think I just figured this out.  You need to do a "makemigrations" on your tenants app (in the instructions, it is called "customers"). This step is missing from the instructions:

```
python3 manage.py makemigrations tenants
Migrations for 'tenants':
  tenants/migrations/0001_initial.py
    - Create model Client
    - Create model Domain
```

Then do:

```
python3 manage.py migrate_schemas --shared
[standard:public] === Starting migration
[standard:public] Operations to perform:
[standard:public]   Apply all migrations: admin, auth, contenttypes, core, tenants, sessions, sites
[standard:public] Running migrations:
[standard:public]   Applying tenants.0001_initial...
[standard:public]  OK
```

Then:

`python3 manage.py migrate_schemas`

Works as expected.

**Comment by iamunadike** [comment]
This was fixed with ensuring the order of your apps seperations is intact:
Ensure your apps is arranged using this approach below if and run makemigrations first 

SHARED_APPS = (
    'django_tenants',  # mandatory
    'tenants',  # => customers aka tenants live here
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',

    # third_party_apps


)
TENANT_APPS = (
    # The following Django contrib apps must be in TENANT_APPS
    # my_apps
    'django.contrib.contenttypes',


    'django.contrib.auth',
    'django.contrib.admin',
    # third_party_apps
)
# Application definition

INSTALLED_APPS = [
    'django_tenants',  # mandatory
    'tenants',  # => customers aka tenants live here
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #main_apps
    'accounts',
    'core',

    #third_party
    'django_filters',

    'corsheaders',
    'simple_history'
]
