### ISSUE TITLE
Support for Django 4

### ISSUE THREAD

**Issue by abadger1** [django-tenants/django-tenants#701]
The conflict is caused by:
    The user requested Django==4.0
    django-tenants 3.3.4 depends on Django<4.0 and >=2.1

Can not install django-tenants when using Django 4

**Comment by abadger1** [comment]
https://github.com/robalar/django-tenants/tree/support-django-4.0

Looks like this is already in progress - how can I check this out ?

**Comment by tomturner** [comment]
OBE #700
