### ISSUE TITLE
ModuleNotFoundError: No module named 'django_tenants'

### ISSUE THREAD

**Issue by madeinquant** [django-tenants/django-tenants#720]
Following the [Quickstart: Compose and Django (docker)](https://docs.docker.com/samples/django/) to build a django application in a docker. After that, install "django_tenants' with standard procedures, when I start the application with `docker-compose up`, I got the above error message. `"ModuleNotFoundError: No module named 'django_tenants'"`
If I remove 'django_tenants' in settings.py, the application can be start with "docker-compose up" normally.
Please feel free to comment.

Environment
Python 3.9.9 with virtual environment

```
INSTALLED_APPS = [
    'django_tenants',
    #.....
```

1. Checking with python console, the library has been installed successfully.
```
% ./manage.py shell
Python 3.9.9 (main, Nov 21 2021, 03:23:42)
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import django_tenants
>>>
```
2. Checking with pip, the library has been installed successfully.
```
% pip show django_tenants
Name: django-tenants
Version: 3.4.2
Summary: Tenant support for Django using PostgreSQL schemas.
Home-page: https://github.com/django-tenants/django-tenants
Author: Thomas Turner
Author-email: tom@twt.me.uk
License: MIT
Location: /Users/Shared/Relocated_Items/Security/eUSB/sync/python/projects/venv/lib/python3.9/site-packages
Requires: Django
Required-by:

```

**Comment by tomturner** [comment]
I suggest you watch the youtube video on how to get started

**Comment by madeinquant** [comment]
Thanks for you reply. Watched the video on YouTube. Because the application has been implemented in a docker with single user. I would convert this application into a multi-tenant application.

**Comment by madeinquant** [comment]
Problem fixed, thanks for your comment. 

The problem is that 
1.  Create a virtual environment for docker installation.
2. Prepare `docker-compose.yml` and `Dockerfile`
3. Create the Django project by running the docker-compose run command. `docker-compose up`
4. Unfortunately, a incorrect version of python is executed in the virtual environment. because `alias python=/usr/local/bin/python3` in .zshrc
5. remove the alias in .zshrc
6. Problem fixed.
