### ISSUE TITLE
How to do a data migration for all tenants?

### ISSUE THREAD

**Issue by butla** [django-tenants/django-tenants#721]
Is it possible to run a data migration (`migrations.RunSql` or `migrations.RunPython`) in the tenant schemas?
I didn't found anything in the docs or in the issues about it.

I've been also trying to hack something on my own with `RunPython`, but it looks like those steps are getting omitted when Django Tenants is enabled. Eventually, Django migrations [asks the "router"](https://github.com/django/django/blob/main/django/db/migrations/operations/special.py#L185) whether it can do the migration, but the `TenantSyncRouter` [never responds](https://github.com/django-tenants/django-tenants/blob/master/django_tenants/routers.py#L29) with `True`.

I've tried running both `manage.py migrate` and `manage.py migrate schemas`.
Am I missing something?

**Comment by mikicz** [comment]
It's possible, I've done both RunSQL and RunPython.

Are you creating the data migration in a tenanted app (in `TENANT_APPS`) or in a public app (`SHARED_APPS`)? Data migrations on tenant schema will only work from a tenanted app.

**Comment by tomturner** [comment]
I write one off management script that loops round all tenants.

**Comment by butla** [comment]
It's in a "tenanted" app... Oh. :facepalm: Ok, I know what it was (most probably). During my tests I didn't reset the `django_migrations` table inside the tenant schemas...

Ok. Sorry for the spam. Closing.

**Comment by butla** [comment]
yup, the usual RunPython recipe from Django docs works like a charm across schemas. Sorry to bother :)
