### ISSUE TITLE
TENANT CREATION ERROR

### ISSUE THREAD

**Issue by mugendi-gitonga** [django-tenants/django-tenants#724]
I have correctly installed django-tenants and setup the public tenant.
When I try to create the first tenant, the migrations start to run but then I get an error, ValueError: Field 'id' expected a number but got 'null'.
If I create a schema directly in the DB then run migrations, it fails when trying to run one of the tenant_apps migrations with the same error above.
What could be the problem?
![d-t1](https://user-images.githubusercontent.com/89004329/152135143-49fe7032-475b-49dc-ae0f-7fca1e263067.png)
![d-t3](https://user-images.githubusercontent.com/89004329/152135147-e7562a1c-5d54-47b1-a7db-bbeea574d789.png)
![d-t2](https://user-images.githubusercontent.com/89004329/152135151-c129970c-60f4-4f05-a1d3-a2c0f9d15106.png)

**Comment by paulonteri** [comment]
What do your tenant models look like?

**Comment by mugendi-gitonga** [comment]
I fixed it bro
There was an error in my migrations which I corrected and everything worked smoothly
