### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by junaooaks** [django-tenants/django-tenants#728]
hey guys,
User authentication on each schema 
how I select specific schema do validate the user? using simple jwt I need to customize the authentication with email, password and tenant subdomain? because the user coming most the time from a global domain example : www.example.com/login in this case the user input data is email, password, subdomain 
in that case I will check if tenant(subdomain) exist after that check the authentication in user table for that specific tenant

**Comment by tomturner** [comment]
Have a look at django tenant users project

**Comment by io-ma** [comment]
Implemented something similar. You can have a custom auth backend in which you check that the subdomain name is equal to the subdomain claim on the JWT token. 
You can either use a schema_name claim or a subdomain, your choice. Similarly, you can add an email claim on your JWT token.
