### ISSUE TITLE
Associating contrib.sites to tenants

### ISSUE THREAD

**Issue by daniel-butler** [django-tenants/django-tenants#729]
Hi this project seems great! I was wondering what it would look like to be able to map sites to a given tenant.

For example, the Django application is set up to receive requests from `example.com`, `wowcool.com`, `lookatme.com` and it also has the tenants configured for each of these like below:

```py
{
  "example.com": "tenant1",
  "wowcool.com": "tenant2",
  "lookatme.com": "tenant3",
}
```

The default or main domain/site is: `mainsite.com`

I would like to keep all of the standard functionality like `tenant1.mainsite.com` serving all of the data for tenant1, but also have `example.com` work the same as if it was `tenant1.mainsite.com`

Is it possible to associate one or many sites from [contrib.sites](https://docs.djangoproject.com/en/4.0/ref/contrib/sites/) to the tenant model. If it is what possible pitfalls are there?

Thank you!

**Comment by daniel-butler** [comment]
Another option, I have been thinking through, is to use the webserver in front of Django to convert the domains to `tenant.base_host` before it gets to Django. I could see there being problems when sending out emails with links or how to get the configuration updated automatically when a new tenant is created.

**Comment by daniel-butler** [comment]
Ok, I was incorrectly assuming the domain name was a sub domain of the main domain. 

Do you think it makes sense to even bother with `contrib.sites`?

**Comment by tomturner** [comment]
Don’t bother with control.sites

**Comment by daniel-butler** [comment]
Walking through the tutorial answered all of my questions. Thank you picking up and running with this project!
