### ISSUE TITLE
Django Tenant does not work with pytest fixtures functional test 

### ISSUE THREAD

**Issue by iamunadike** [django-tenants/django-tenants#738]
Assuming the Name of my app is  'myapp'

@pytest.fixture
def setup():
    tenant = Tenant.objects.last()
    yield tenant

@pytest.mark.django_db
def test_some_thing_using_functional_test_approach(setup):
     #some test  code... 
     

The above causes error the myapp_model_name DOES NOT EXIST  . This is because they live in schemas and therefore how do I ensure the Tenant or SCHEMA is created in this functional test before it runs especially with Pytest Fixtures and test itself

**Comment by mikicz** [comment]
As the `setup` fixture is the tenant, you can do this in the test case to activate the tenant

```
@pytest.mark.django_db
def test_some_thing_using_functional_test_approach(setup):
    with setup:
       # test code
```

This would obviously get pretty boring writing it in every test, so at our company we essentially this, which activates the tenant returned from `setup` automatically for all tests

```
@pytest.fixture
def setup():
    tenant = Tenant.objects.last()
    yield tenant

@pytest.fixture(scope="function", autouse=True)
def activated_schema(setup):
    with setup:
        yield
```

**Comment by iamunadike** [comment]
Hello I tried your approach but it is not working, I dont know what this case is , I actually need a schema to be exposed during this functional test,  
with django-tenants:
using class approach I can subclass or extend  the test class using e.g

class CustomApiTest(TenantTestCase):
      #constructor...
sincee TenantTestCase automatically wraps the testclass and creates a schema to run databases, tenants and domains

so how can this  using a functional approach

**Comment by iamunadike** [comment]
to fix this with Pytest
use my code below :)

""" A life saver: """
Follow me on github.com to learn more

```
from rest_framework.test import APIClient
from rest_framework_simplejwt.tokens import RefreshToken


class TenantAPIClient(APIClient):
    """ Builds a wrapper around apiclient to fit tenant based testcases """
    def __init__(self, tenant, enforce_csrf_checks=False, **defaults):
        super().__init__(enforce_csrf_checks, **defaults)
        self.tenant = tenant

    def get(self, path, data=None, follow=False, **extra):
        if "HTTP_HOST" not in extra:
            extra["HTTP_HOST"] = self.tenant.get_primary_domain().domain

        return super().get(path, data, **extra)

    def post(self, path, data=None, follow=False, **extra):
        if "HTTP_HOST" not in extra:
            extra["HTTP_HOST"] = self.tenant.get_primary_domain().domain

        return super().post(path, data, **extra)

    def patch(self, path, data=None, follow=False, **extra):
        if "HTTP_HOST" not in extra:
            extra["HTTP_HOST"] = self.tenant.get_primary_domain().domain

        return super().patch(path, data, **extra)

    def put(self, path, data=None, follow=False, **extra):
        if "HTTP_HOST" not in extra:
            extra["HTTP_HOST"] = self.tenant.get_primary_domain().domain

        return super().put(path, data, **extra)

    def delete(self, path, data=None, follow=False, **extra):
        if "HTTP_HOST" not in extra:
            extra["HTTP_HOST"] = self.tenant.get_primary_domain().domain
        return super().delete(path, data, **extra)

@pytest.fixture
def api_client(request, tenant):
    client = TenantAPIClient(tenant)
    user = request.getfixturevalue(request.param)
    token = RefreshToken.for_user(user).access_token
    client.credentials(HTTP_AUTHORIZATION='JWT ' + str(token))
    yield client

```
