### ISSUE TITLE
Django Tenant: Support for Horizontal Scaling

### ISSUE THREAD

**Issue by RuchitMicro** [django-tenants/django-tenants#740]
There is no reference/documentation on how to horizontally scale the database with respect to this package.
Can you please provide some literature?

**Comment by tomturner** [comment]
As it's a normal PosgreSQ database there are plenty of resouces online for this.

**Comment by RuchitMicro** [comment]
Thank Tom for replying so quickly, I would like to know how I can have public schema in one main postgresql server and schemas in other distributed servers. I know this is not a topic related to this package but many of my colleagues who use this package have the same question. If you have some link or maybe a topic name to research with on google, it would be a great help. Thank you once again :)

**Comment by tomturner** [comment]
I suggest posting on stackoverflow
