### ISSUE TITLE
Brand new tenants can't apply some old migrations due to constraint introspection changes

### ISSUE THREAD

**Issue by veep** [django-tenants/django-tenants#744]
We have a migration that creates a `unique_together` constraint containing two fields.  A later migration deleted that constraint. This deletion migration fails with the latest django-tenants that has changed the get_constraints behavior.

This seems to happen only against AWS RDS postgres and not locally hosted postgres on developer machines.

My guess is that the new constraint lookup code is not canonicalizing the order of the two fields in the constraint, given that it reproduces only on one postgres implementation and not the other. (Though I am not 100% sure about this).

Going back and editing the four year old migration file to swap the order of the unique_together fields "fixes" the issue, but this isn't a great solution in general. I don't know how to find all the constraints that the new 3.4.2 code could fail to find in the future. Any constraint we try to modify in the future could fail.

**Comment by tomturner** [comment]
Personal I don't use RDS. I would try and reset the migrations if it was me.
