### ISSUE TITLE
How to get current tenant id for use in context processor

### ISSUE THREAD

**Issue by macumhail** [django-tenants/django-tenants#746]
In my tenant model I have a company name field. I am attempting to create a context processor to make the company name available for use in each account (in the navbar for example). I can get the context processor to work if I filter by Tenant id. However I have not been able to figure out how to get the current Tenant id. 

The context processor (with id hard coded):
```
from company_accounts.models import Tenant
from django.shortcuts import render

def cname(request):
    company = Tenant.objects.get(id=2)
    return ({'cname': company})
```

**Comment by tomturner** [comment]
Look at the request object it has it there.

**Comment by macumhail** [comment]
Thank you, Tom. Could you share a little about how to do this? I am new to Django and python and very new to django-tenants.

**Comment by tomturner** [comment]
Django Tenants is a quite advanced django package it going to be hard learn django with it!  However what you is require is 'request.tenant'. I would recommend that you use ide such as pycharm as this will help you lots as you can put break points in the code.

**Comment by macumhail** [comment]
Thank you, Tom. That helps. I am using PyCharm - and learning about how to use its capabilities.
