### ISSUE TITLE
tenant_superuser can login into other tenants 

### ISSUE THREAD

**Issue by VaZark** [django-tenants/django-tenants#756]
When a superuser is created using `create_tenant_superuser`, I had expected that the user would have superuser access only to the schema it has been configured for. However, the user is able to view the admins of all the tenants on the system 

## Steps to reproduce

1. Two tenants: `owner` and `tenant_1`
2. Custom user created in shared app
3. Created tenant superuser using `python manage.py create_tenant_superuser --username=admin --schema=tenant_1 `

## Issue

The newly created "admin" user is able to login to tenant owner model as well

**Comment by cehceh** [comment]
you must have to separate the admin site like 
`from tenant_type_one_only.models import TableOne, TableTwo
from django.contrib.admin import AdminSite

# Register your models here.

class MyAdminSite(AdminSite):
    site_header = 'Admin Site For Type One only'

admin_site = MyAdminSite(name='type1-admin')
admin_site.register(TableOne)
admin_site.register(TableTwo)`

**Comment by VaZark** [comment]
@cehceh Thanks for the heads up. It partially solves my problem but not completely.

The separation of admin sites only separates the different types of apps in the `MULTI_TENANT_TYPE=True`

Is there not a way or configuration to isolate the superuser to each subdomain/schema configured?  

## Setup 

1. `HAS_MULTI_TYPE_TENANTS = True`
2. Standard admin for owner/shared app
3. Custom Admin for tenant apps

## Expected behaviour

1. `create_tenant_superuser` is isolated to each subdomain / schema

## Issue faced

1. Users of tenant subdomains can login into other admin pages of same app type
    Eg : superuser created for `tenant-1.localhost` is able to login to `tenant-2.localhost` . 
2. Works as expected and does not allow superuser of `tenant-1.localhost` to login to `localhost` (which is a shared app admin)

## Thoughts

1. Should I create a separate user admin for each tenant?
2. Does using a custom user model (derived from AbstractUser) change anything ? 
3. Should moving AbstractUser to Tenant App work (I only got errors) ?

**Comment by VaZark** [comment]
Removing my custom `AbstractUser` fixes the issue but how do I add custom parameters on top of the user model.

1. Adding `AbstractUser` to any app on the shared models' list, adds the user to the common schema and allows users to see other subdomains
2.   Adding `AbstractUser` to any tenant app, throws an error. (since AUTH_USER_MODEL is in the tenant app) 

Is there a way to have separate customised user models for each tenant?

**Comment by VaZark** [comment]
Fixed the issue by creating a custom AbstractUser class in a separate app and using that in both shared and the tenant apps lists.

This ensures when migrations are applied, the custom user model is shared by all apps.

**Comment by VaZark** [comment]
Let me know if you want to add this to the docs. :)

**Comment by cehceh** [comment]
It's good to hear that your issue solved. But I'm not one of the contributors of this package, Only I'm working with it...
Any ways, Of course it's a normal behavior because you added the custom user in the public schema only(so my answer doesn't help).
You must add the custom user model (authentication app) in every type in settings to be sure the every schema has a separate table to manage user authentication, hence every schema will have its super user and my code will work as expected.
