### ISSUE TITLE
Configure in Django tenants django_tenants.postgresql_backends in github actions postgres to avoid cause failing?

### ISSUE THREAD

**Issue by iamunadike** [django-tenants/django-tenants#770]
How can I configure github actions for django tenants , since github uses postgresql service image, how do I tell github to use the engine django_tenants.postgresql_backends in the .github/workflows/ci.yml ??
AttributeError: 'DatabaseWrapper' object has no attribute 'set_schema'

**Comment by iamunadike** [comment]
@tomturner

**Comment by iamunadike** [comment]
can you help workflows with django_tenants .yml config, since they both use different engines, postgres is default to github and django_tenants.postgresql_backends is different somehow

**Comment by tomturner** [comment]
Personal I use docker with git hub actions.

**Comment by iamunadike** [comment]
@tomturner Just a clarification despite I am familiar is it supposed to be python manage.py makemigrations; python manage.py migrate or just python3 manage.py migrate_schemas

**Comment by iamunadike** [comment]
I fixed it , without docker approach, using dj_database_url and adding removing migrations from my gitignore
thanks
