### ISSUE TITLE
Django queries on PyCharm python console throws django.db.utils.ProgrammingError: relation "model" does not exist.

### ISSUE THREAD

**Issue by RecNes** [django-tenants/django-tenants#786]
Queries are running fine with runserver and python console on any terminal

But, when it's come to PyCharm python console, queries are throwing 
`django.db.utils.ProgrammingError: relation "model" does not exist.`
error.

The PyCharm python console setup like this:

![Screen Shot 2022-06-28 at 15 44 01](https://user-images.githubusercontent.com/7573523/176181757-5468ac4b-c09a-4413-82b1-1e431dc7be5b.png)

I think tenants app, somehow, does not intercept with django queries when running on PyCharm python console.

Any idea to fix this issue?

**Comment by iamunadike** [comment]
I advise you dont use a IDE console as it does not have all the necessary access to the tools for running a migration
that said, cross check properly your configuration against the standard provided by django-tenants
Also ensure that you fix this within the middlewares and INSTALLED_APPS, TENANT_APPS and SHARED_APPS, if all is properly set IT will work
No further questions, just close the Issue with this answer
