### ISSUE TITLE
How to use fixtures in TenantTestCase

### ISSUE THREAD

**Issue by Brechard** [django-tenants/django-tenants#793]
I am migrating to a multi-tenant app from an MVP working alone that now has to accept several clients. Everything seems to work except the test cases that we had written before. It seems to me that the problem is the fixtures are not loading correctly. There is no error or message about the fixtures anywhere. The tests fail because the database is not filled and the objects are not there to get.

I am using rest_framework, I have also checked [issue #119 ](https://github.com/django-tenants/django-tenants/issues/119) to see if it was a problem of setUpTestData not being called, but when I implemented the suggestions the DB is still empty.

I have also tried implementing the pull request [#147](https://github.com/django-tenants/django-tenants/pull/147) but I get an error when doing it (django.core.management.base.CommandError: Unknown command: 'migrate_schemas')

Lastly, I tried to call manually the loaddata command with the tenant without success.

```
call_command("tenant_command", "loaddata", "fixtures_for_tests.json", schema="test", verbosity=0)
```

but I get this error:

```
Traceback (most recent call last):
  File "/app/coreapp/tests/test_setup.py", line 147, in setUpClass
    call_command("tenant_command", "loaddata", "fixtures_for_tests.json", schema="test", verbosity=0)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django_tenants/management/commands/tenant_command.py", line 52, in handle
    call_command(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 105, in call_command
    app_name = get_commands()[command_name]
TypeError: unhashable type: 'list'

```

Are there any changes needed for loading the fixtures in tests? What could be the issue otherwise? I could find very few info about fixtures in the docs

**Comment by Brechard** [comment]
Since I was using setUpTestData several changes had to be done, the most important thing is that fixtures have to be separated into public and per-tenant fixtures. The following code should work:

```
from django.test import TestCase
from django_tenants.test.cases import FastTenantTestCase

class TestBase(FastTenantTestCase):
    fixtures = ["fixtures_for_tests.json"]
    tenant_client = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    @classmethod
    def tearDownClass(cls):
        TestCase.tearDownClass()
        super().tearDownClass()

    @classmethod
    def setUp(cls):
        connection.set_tenant(cls.tenant)

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        connection.set_schema_to_public()
        # Ensure that fixtures are loaded here
        TestCase.fixtures = cls.fixtures
        TestCase.setUpClass()
        connection.set_tenant(cls.tenant)
        cls.setUpTestData()

    @classmethod
    def setUpTestData(cls):
        connection.set_tenant(cls.tenant)
```

**Comment by SilverFoxA** [comment]
@Brechard How did you solve this issue? I'm still facing the same.

```python
call_command('tenant_command', 'loaddata', '--schema={0}'.format(client.schema_name))
```

I have even tried the interactive version

![Screenshot 2023-01-15 at 7 46 25 PM](https://user-images.githubusercontent.com/6983070/212546067-a1c5532d-98b6-4f44-b411-34cec10c1159.png)

I was creating a client from the admin dashboard.

**Comment by Brechard** [comment]
@SilverFoxA the issue you are facing is that the command is asking you the schema name and you are sending : SCHEMA_NAME - DOMAIN_NAME. 

When you send the "?" command it outputs a list with that format therefore, you have 2 tenants created:
1. schema name = "public" and with domain name = "admin.localhost"
2. schema name = "demo" and with domain name = "demo.localhost"

When asked for the tenant schema you should either send "public" or "demo". Since I did not manage to make that command work in the tests I created a modification of FastTenantTestCase to use as I mentioned in my last command.
