### ISSUE TITLE
Static files

### ISSUE THREAD

**Issue by io-ma** [django-tenants/django-tenants#824]
Hello friends,
Was thinking: why do we want each tenant to have their separate static files when those are basically the same for all tenants (I mean the admin statics etc)? Media files are different, but how about keeping a single set of static files in a single dir, say in aws s3 or something similar , without splitting the static dir on that bucket? Tried to do that but I guess I would need to write a custom backend, right?

**Comment by tomturner** [comment]
You don't need to have different static you can use the same. Having different staic is only an option. Infact that how I do it.
