### ISSUE TITLE
Can't login to the Admin of public tenant

### ISSUE THREAD

**Issue by SergeyDev1996** [django-tenants/django-tenants#825]
Hello. I have red the documentation a few times and watched the availalbe videos a few times, so the code should be good. I user create_tenant_superuser to create a tenant, however, still can not login to the Admin page of my public schema, I just do not receive any response, nothin happens when I am trying to login: 
[](https://prnt.sc/X_se-QerujV-)
My installed apps are the following:
`SHARED_APPS: 'django_tenants',
    'django.contrib.auth',
    'django.contrib.staticfiles',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.admin',
    'django.contrib.messages',
    'tenant_users.permissions',
    'tenant_users.tenants',
    'rest_framework',
    'rest_framework.authtoken',
    'user',
    'drf_spectacular',
    'restaurant_shared',
    'tenanted_api',
TENANT_APPS: 
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.admin',
    'restaurant_tenanted',
    'tenant_users.permissions'
`

and my urls are the following: 
`urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/tenant/', include('restaurant_tenanted.urls')),
    path('api/public/', include('restaurant_shared.urls')),
    path('api-token-auth/', views.obtain_auth_token),
    path('home/', home_view),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/doc/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

]
`

**Comment by tomturner** [comment]
To login to the main public schema you will need to use the normal createsuperuser as it not a tenanted app.

**Comment by SergeyDev1996** [comment]
> @SergeyDev1996 To login to the main public schema you will need to use the normal createsuperuser as it not a tenanted app.

Yes, I have tried that, still can not login. Also, I have deleted django.contrib.sites app, because if i don't delete it, the admin won't load at all with the following error: 
![Без названия (7)](https://user-images.githubusercontent.com/105145962/188106464-645ad304-2479-4e7f-8ee9-1009fffa861c.png)
P.S sorry for pasting the images, this is is my first time creating an issue, it looked very bad if i tried to paste the code.
