### ISSUE TITLE
Reset User Passwords

### ISSUE THREAD

**Issue by rmendes1** [django-tenants/django-tenants#843]
Hello, everyone.

Firstly, thanks to the maintainer of this project. You have helped us a lot so far!

I wrote this issue because of some doubts that I have had. 

I am trying to add a feature to a project I collaborate with that uses Django Tenants. It consists in having the tenant users redefine their passwords if they forget it, through a confirmation sent to their email addresses.

Is it possible to use Django's default authentication system for password reset in a project with Tenants? Or it is provided some type of functionality to make it work in Django Tenants without having to use the former one?

**Comment by mcroni** [comment]
treat this library like just a regular django library, most of the abstractions are done on the database level this also means you can still use django's default auth system. Be sure to provide the context (tenant) whose User model you're trying to get access to
