### ISSUE TITLE
ngrok doesn't redirect to tenant subdomain urls

### ISSUE THREAD

**Issue by i0000010** [django-tenants/django-tenants#867]
I'm developing a django project with tenant subdomains such as test.localhost:8000. I've set up a reverse proxy with ngrok that tunnels requests from a public url, eg `test.myapp.ngrok.io`, to my tenant subdomain url, eg `test.localhost:8000.` The result is 404 page not found because django is searching the public urls, not the tenant urls, to service the request. Is there a known solution to this problem?

**Comment by JayDarjiAubergine** [comment]
Did you find a way to make this work @i0000010?
