### ISSUE TITLE
Tenant-aware static file handling targets schema usage rather than domain specific schema

### ISSUE THREAD

**Issue by SilverFoxA** [django-tenants/django-tenants#868]
@tomturner This is an amazing package that you have created, thank you for that.

I'm trying to have two different UI for the system admins and the clients.

```python
STATICFILES_FINDERS = [
    "django_tenants.staticfiles.finders.TenantFileSystemFinder",
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

MULTITENANT_STATICFILES_DIRS = [
    os.path.join( os.path.join(BASE_DIR, "assets"), "tenants/%s" ),
]
```

My static file structure looks something like this

```shell
assets
-- tenants
--- public
---- system admins specific styles
```

User app is in the shared app

```python
SHARED_APPS = (
    ....,
    'apps.user',
)
```

The clients will be able to view their billing details and subscriptions from their accounts page.
The problem here is because these are shared apps, the style that's being used is of the `public` schema whereas the styles of the `tenant` schema should have been used based on the domain.

Looking forward to any input otherwise would have to handle it with a `templatetag`.

**Comment by tomturner** [comment]
not something I have done might be worth asking on stackoverflow.
