### ISSUE TITLE
all_tenants_command always return early if a command has no argument

### ISSUE THREAD

**Issue by tdcdev** [django-tenants/django-tenants#871]
I think a bug was introduced here: https://github.com/django-tenants/django-tenants/commit/51442a2d6749e7cabe85fbf2daeceb20887e9f0b

If a command is called like:
```
python manage.py all_tenants_command my_super_command
```

then `all_tenants_command` will always return early.

**Comment by oleksiyVeretiuk** [comment]
@tomturner what do you think about that?
