### ISSUE TITLE
django-tenant doesn't play well alongside CustomUser (AbstractUser) !

### ISSUE THREAD

**Issue by infosrabah** [django-tenants/django-tenants#881]
Hi,

How did you solve your issue with CustomUser, I have  admin that causing this error :

I cloned django-tenants from git, it worked with default auth User perfectly play with it, create tenants, added some data to the tenant1 and tenant2 TableOne,,  ..... everything work like a charm

but when I added  "accounts" app with custom user (AbstractUser), and define : AUTH_USER_MODEL = 'accounts.User' in settings.py

So basically I left everything as it is (I didn't touch anything elese), it didn't work and throw me an error

Here's a trace :

```
(venv) rado@znb:~/dev/junky-projects/django-tenants/examples/tenant_tutorial$ python manage.py migrate_schemas --shared
[standard:public] === Starting migration
[standard:public] Operations to perform:
[standard:public]   Apply all migrations: accounts, admin, auth, contenttypes, customers, sessions, tenant_only
[standard:public] Running migrations:
[standard:public]   Applying contenttypes.0001_initial...
[standard:public]  OK
[standard:public]   Applying contenttypes.0002_remove_content_type_name...
[standard:public]  OK
[standard:public]   Applying auth.0001_initial...
[standard:public]  OK
[standard:public]   Applying auth.0002_alter_permission_name_max_length...
[standard:public]  OK
[standard:public]   Applying auth.0003_alter_user_email_max_length...
[standard:public]  OK
[standard:public]   Applying auth.0004_alter_user_username_opts...
[standard:public]  OK
[standard:public]   Applying auth.0005_alter_user_last_login_null...
[standard:public]  OK
[standard:public]   Applying auth.0006_require_contenttypes_0002...
[standard:public]  OK
[standard:public]   Applying auth.0007_alter_validators_add_error_messages...
[standard:public]  OK
[standard:public]   Applying auth.0008_alter_user_username_max_length...
[standard:public]  OK
[standard:public]   Applying auth.0009_alter_user_last_name_max_length...
[standard:public]  OK
[standard:public]   Applying auth.0010_alter_group_name_max_length...
[standard:public]  OK
[standard:public]   Applying auth.0011_update_proxy_permissions...
[standard:public]  OK
[standard:public]   Applying auth.0012_alter_user_first_name_max_length...
[standard:public]  OK
[standard:public]   Applying accounts.0001_initial...
[standard:public]  OK
[standard:public]   Applying admin.0001_initial...
Traceback (most recent call last):
  File "/home/rd/dev/django-tenants/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "User" does not exist
```

and here the setting.py :

```
ROOT_URLCONF = 'tenant_tutorial.urls_tenants'
PUBLIC_SCHEMA_URLCONF = 'tenant_tutorial.urls_public'

# Python dotted path to the WSGI application used by Django's runserver.
WSGI_APPLICATION = 'tenant_tutorial.wsgi.application'

SHARED_APPS = (
    'django_tenants',  # mandatory
    'customers',  # you must list the app where your tenant model resides in

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

TENANT_APPS = (
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.sessions',
    'django.contrib.messages',
    'accounts', 
    'tenant_only',
)

TENANT_MODEL = "customers.Client"  # app.Model

TENANT_DOMAIN_MODEL = "customers.Domain"  # app.Model

TEST_RUNNER = 'django.test.runner.DiscoverRunner'

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

###############
# Auth Config #
###############
AUTH_USER_MODEL = 'accounts.User' #changes the built-in user model to ours
```

Any tips how to solve this please ? Thank you

**Comment by bgunebakan** [comment]
You need to delete 'django.contrib.admin' from SHARED_APPS. Django tries to access User model when migrating admin app but there is no User table in the public schema. You may need to clean migrations and delete DB before new migrations.

**Comment by bonfimjustino7** [comment]
I had the same question, and it worked for me. Thank you very much!

**Comment by infosrabah** [comment]
Hi @bonfimjustino7,

How did you make it work ?

**Comment by bonfimjustino7** [comment]
Hi @infosrabah 

Set my settings.py this way

![image](https://user-images.githubusercontent.com/47996966/217813342-158d7512-db77-47ea-aaf4-2dc9b257f796.png)

**Comment by infosrabah** [comment]
@bonfimjustino7 Thank you for the answer.

Ah haaaa I got you :)

That's why..... you took off all the apps from the "SHARED_APP" that explain everything ;) and that's why there will be no issue or bug.

So you went completely isolated approach (good).

But how you gonna deal with a public tenant ??? like a landing page or the main website, for tenant subscription or registration ???, you gonna need some apps, like : 
 'django.contrib.sessions',

**Comment by bonfimjustino7** [comment]
Hi @infosrabah,

I created a tenant with schema 'public' and I can register the other tenants from it.

**Comment by anugrahsoft** [comment]
Hi bonfimjustino7,

Thank's for the tip.

**Comment by umairahmed515** [comment]
Hi @bonfimjustino7 

I have done the similar thing in my settings.py - I have an additional use-case here that is I want a sort of a global super user who can login to any tenant admin site. Is there any way I can achieve that with these settings?

**Comment by anugrahsoft** [comment]
As I know the only way to achieve this is to create an super admin user in every tenant, but it is hided to all other tenant users, like when you click on the users list, it will not appear.
