### ISSUE TITLE
Is it possible to have two AUTH_USER_MODEL? One for tenant, one for public.

### ISSUE THREAD

**Issue by adambirds** [django-tenants/django-tenants#884]
So, just an overview of my app so it makes sense. This will be a SaaS application.

`example.com` = The front page of my SaaS site which advertises my product.
`example.com/dashboard` = The dashboard for me to manage and monitor things such as billing etc.

The above all use the public schema.

`tenant1.example.com` = The frontpage to the tenants support page
`tenant1.example.com/staff-dashboard` = The dashboard for tenants staff to manage and respond to tickets.
`tenant1.example.com/customer-dashboard` - The dashboard for the customer to see their tickets etc.

The above use their individual tenant schema.

Now I would like to extend the default User model in both the public schemas and the tenant schemas but obviously with separate models because the tenants users will require different fields to the public schemas users. So how do I do this as I can only set `AUTH_USER_MODEL` once.

**Comment by tomturner** [comment]
No however to get round the problem use a one to one field to extend the modal then you can put any changes in the tenant app

https://docs.djangoproject.com/en/4.1/ref/models/fields/#django.db.models.OneToOneField

**Comment by adambirds** [comment]
@tomturner okay, do you think it would be difficult to add the ability to have two. Happy to code it myself, but wondering if you have any tips/advice on how I could implement that? Thanks

**Comment by tomturner** [comment]
I don't see the need for it as the one 2 one field works fine. You might many to look at django tenant users

**Comment by adambirds** [comment]
Came up with a different solution for this with just a single custom User model to allow me to have email auth and email being a required field and then one-to-one for others so closing this.
