### ISSUE TITLE
sqlite support ?

### ISSUE THREAD

**Issue by patelgopal1213** [django-tenants/django-tenants#886]
is there a road map or plan to implement sqlite support for this ?

**Comment by baseplate-admin** [comment]
I Don't think thats possible to do. As SQlite doesn’t support schemas like postgres.

More info on : https://stackoverflow.com/questions/33960762/does-sqlite-support-multiple-schematas-within-the-same-database#33962375

**Comment by tomturner** [comment]
Nope and never will be.  DT only supports PostgeSQL
