### ISSUE TITLE
User based routing

### ISSUE THREAD

**Issue by mdefeche** [django-tenants/django-tenants#887]
Hello,

I'd like to know if it's possible to make the routing based on the user and not based on the domain / directory. We have a SaaS solution (so all users will hit the same URL) and an API (DRF). It will also prevent an authenticated user from accessing another tenant's data.

This would require to:
* have a FK to the Client(TenantMixin) model in the custom user model 
* have a custom middleware to do the routing based on the user. That middleware would be listed after AuthenticationMiddleware
* have the user table in the shared apps

Is this doable ? Does it makes sense or I'm taking this the wrong way ?

**Comment by tomturner** [comment]
Have a look at django tenant users. Might do what you want
