### ISSUE TITLE
while run management command got an error of maximum recursion depth exceeded

### ISSUE THREAD

**Issue by mdhvcd** [django-tenants/django-tenants#889]
when I run the management command using `python manage.py tenant_command` gives an error of maximum recursion depth exceeded. I think when it comes here in code 
``
`def __new__(cls, *args, **kwargs):
      """
      Sets option_list and help dynamically.
      """
      obj = super().__new__(cls, *args, **kwargs)
      print([obj.COMMAND_NAME],  "=====")
      app_name = get_commands()[obj.COMMAND_NAME]
      if isinstance(app_name, BaseCommand):
          # If the command is already loaded, use it directly.
          print("=-=-==-")
          cmdclass = app_name
      else:
          print("==-------------------")
          print(app_name, obj.COMMAND_NAME)
          cmdclass = load_command_class(app_name, obj.COMMAND_NAME)

      # prepend the command's original help with the info about schemata iteration
      obj.help = "Calls %s for all registered schemata. You can use regular %s options. " \
                 "Original help for %s: %s" % (obj.COMMAND_NAME, obj.COMMAND_NAME, obj.COMMAND_NAME,
                                               getattr(cmdclass, 'help', 'none'))
      return obj`
Code comes in else part and call load_command_class and in load_command_class 
`def load_command_class(app_name, name):
    """
    Given a command name and an application name, return the Command
    class instance. Allow all errors raised by the import process
    (ImportError, AttributeError) to propagate.
    """
    module = import_module("%s.management.commands.%s" % (app_name, name))
    return module.Command()
`
it will call module.Command()
and that's how error occur

**Comment by cs-satish-mishra** [comment]
@mdhvcd Hi, What was the issue and fix?
