### ISSUE TITLE
django call_command fails when called with command_name="tenant_command" args="loaddata example.yaml"

### ISSUE THREAD

**Issue by jackkweyunga** [django-tenants/django-tenants#891]
tenant_command fails to discover loaddata as the command_name and example.yaml as its argument when recalling call_command. Instead, it discovers a list; ["loaddata", "example.yaml"] as the call command. This leads to a TypeError: 

TypeError: unhashable type: 'list'

Hence one cannot write such custom management commands  utilizing the "tenant_command"

**Comment by tomturner** [comment]
Fixed
