### ISSUE TITLE
Migration fails for a public schema table with FK to a tenant

### ISSUE THREAD

**Issue by sergeysviezhentsev** [django-tenants/django-tenants#909]
I can't perform the migration for a table in a public schema that creates a foreign key to a table in a tenant schema.

In the public schema, I have a user app with a User table with a foreign key on the school table:
```
class TenantUser(AbstractUser):
    student_profile = models.ForeignKey(School, on_delete=models.CASCADE, null=True, blank=True)
```
In the public schema, I have a school app with a School table:
```
class School(models.Model):    
    name = models.CharField(max_length=255, unique=True)
```

When running the migrations command on an empty database or when running tests, during creation of a public schema an error occurs:  `django.db.utils.ProgrammingError: relation "school_user" does not exist`
As I understand it, the error is logical: when creating a public schema, the tenant schema does not yet exist and the foreign key has nothing to refer to.

I couldn't find any solutions for a similar problem in the documentation. Duplicating the tenant application to the `SHARED_APPS`  solved the problem, however, it creates a set of tables in the public schema that will never be used and carries the risk of a delayed bomb that data will be written to them by mistake sooner or later.
Could you recommend the best solution to this problem without using the abovementioned method?

**Comment by sergeysviezhentsev** [comment]
This is not possible because the foreign key specifically points to entity including schema name (`tenant1.school_school`).

**Comment by tomturner** [comment]
Hi you can link a table in a tenant to a table in public however you can't do it the other way round.  Make sure you set related_name='*'.

**Comment by hogking** [comment]
hi tomturner，It seems that there is only related_name='+' in Django. Is this what you mean? @tomturner
