### ISSUE TITLE
OperationalError: out of shared memory when deleting a tenant

### ISSUE THREAD

**Issue by mauroka** [django-tenants/django-tenants#943]
Hi.
We are getting the following error when we try to delete a tenant:
```
OperationalError: out of shared memory
HINT:  You might need to increase max_locks_per_transaction.
```
The error happens when the following line is executed:
https://github.com/django-tenants/django-tenants/blob/6143d27a0c9249bb1059ee9662c5c142e4bc47c8/django_tenants/models.py#L162

Is there a workaround besides increasing the max_locks_per_transaction value?
Thanks.
Regards.

**Comment by mcquadenc** [comment]
Hi @mauroka I Do not analyzed your context, but Did you try this?

[https://stackoverflow.com/questions/40654766/how-to-increase-max-locks-per-transaction](https://stackoverflow.com/questions/40654766/how-to-increase-max-locks-per-transaction)

> you might find ../data/postgresql.conf file, then edit with notepad, set max_locks_per_transaction = 1024 if it looks like # max_locks_per_transaction... you must remove #.
> 
> it must look like that: max_locks_per_transaction = 1024 # min 10
> 
> than save it and restart postgresql


And this is explains in Postgres oficial [documentation](https://www.postgresql.org/docs/15/runtime-config-locks.html#GUC-MAX-LOCKS-PER-TRANSACTION), 
I think the highlight follow can be cause for you case: 

> The shared lock table tracks locks on max_locks_per_transaction * ([max_connections](https://www.postgresql.org/docs/15/runtime-config-connection.html#GUC-MAX-CONNECTIONS) + [max_prepared_transactions](https://www.postgresql.org/docs/15/runtime-config-resource.html#GUC-MAX-PREPARED-TRANSACTIONS)) objects (e.g., tables); hence, no more than this many distinct objects can be locked at any one time**. This parameter controls the average number of object locks allocated for each transaction; individual transactions can lock more objects as long as the locks of all transactions fit in the lock table. This is not the number of rows that can be locked; that value is unlimited. The default, 64, has historically proven sufficient, but you might need to raise this value if you have queries that touch many different tables in a single transactio**n, e.g., query of a parent table with many children. This parameter can only be set at server start.
> 
> When running a standby server, you must set this parameter to the same or higher value than on the primary server. Otherwise, queries will not be allowed in the standby server.

**Comment by mauroka** [comment]
Hi @mcquadenc, thanks for the response.
The problem was that we had relations to the Tenant Model to reference the schema.
We removed those relations and the problem was solved.
