### ISSUE TITLE
MULTI_TENANT_TYPES  no specific migration

### ISSUE THREAD

**Issue by SheezyJay** [django-tenants/django-tenants#947]
I have found a bug. When You have Multi Tenant Types and you migrate its always running migrations for all apps on every tenant (so not just on public, type1...)

Has anyone an idea how to fix this ?

**Comment by tomturner** [comment]
Are you sure. It will look like it runs on all however it only applies on the correct type.

**Comment by SheezyJay** [comment]
Yeah i tried often and i tried the example too. So the migrations are working but all the apps are migration regardless of whether it is a special tenant. 
You will get always relation errors if you have different apps.

**Comment by SheezyJay** [comment]
I'm sorry for the disturbance. I've only now noticed that a custom middleware is accessing a model that doesn't exist there.
