### ISSUE TITLE
Error Creating Restaurant: Unit Testing Issue with TenantTestCase in Django DRF

### ISSUE THREAD

**Issue by elinonga** [django-tenants/django-tenants#975]
**Description**:

I am working on a Django project using Django Rest Framework (DRF) and django-tenants for multi-tenancy. In my unit tests, I'm encountering an error that I need help resolving.

**Issue**:

When running a unit test to create a restaurant using the TenantTestCase, I am getting the following error:
```
Creating test database for alias 'default'...
System check identified no issues (0 silenced).

F
======================================================================
FAIL: test_create_valid_restaurant (django_apis.restaurants.tests.RestaurantCreateTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\OK\BackendProjects\apis\django_apis\restaurants\tests.py", line 55, in test_create_valid_restaurant
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 404 != 201

----------------------------------------------------------------------
Ran 1 test in 4.596s

FAILED (failures=1)
Destroying test database for alias 'default'...
```

**Code**:

Here's the relevant code for the unit test:

```
class RestaurantCreateTest(TenantTestCase):
    tenant = None  # Define a class attribute to store the tenant instance

    @classmethod
    def setup_tenant(cls, tenant):
        tenant.name = "kangaroo"
        tenant.subdomain_prefix = "kangaroo"

        # Store the tenant instance as a class attribute
        cls.tenant = tenant

        return tenant

    def setUp(self):
        super().setUp()
        self.c = TenantClient(self.tenant)

    # Override the get_test_tenant_domain method to specify a custom test domain
    @staticmethod
    def get_test_tenant_domain():
        if RestaurantCreateTest.tenant:
            domain = f"{RestaurantCreateTest.tenant.subdomain_prefix + settings.ORGANIZATION_DOMAIN}"
            return domain
        else:
            return "tenant.test.com"  # Default custom test domain if tenant is not set

    def test_create_valid_restaurant(self):
        url = reverse("Restaurant-list")
        # url = "http://localhost:8000/restaurants/"
        data = {
            "name": "Sample Restaurant",
            "address": "123 Main Street",
            "phone_number": "555-123-4567",
            "email": "sample@example.com",
            "cuisine": "Italian",
            "rating": 4.5,
        }
        response = self.c.post(url, data, format="json")
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)

        # Check if the restaurant object was created in the database
        restaurant = Restaurant.objects.get(name="Sample Restaurant")
        self.assertIsNotNone(restaurant)

        # Check if the response data matches the serialized restaurant
        serializer = RestaurantSerializer(restaurant)
        self.assertEqual(response.data, serializer.data)
```

**Additional Information**:

I'm using django-tenants for multi-tenancy.
The error suggests a 404 status code instead of the expected 201 Created status when creating a restaurant.
I've verified my URL configuration, view names, and tenant setup, but the issue persists.

**Request**:

I'm looking for guidance on how to resolve this error and successfully create a restaurant in my unit test using django-tenants with DRF. Any insights or suggestions would be greatly appreciated. Thank you!

**Comment by Joe3009** [comment]
The Problem is because of the url.configs in for this Multy-tenancy type. The reverse function will only lookup in public so you have to customize the reverse function, here is my example how i solve this:
(the url conf is important: urlconf="ROUTE_WHERE_YOU_DECLARE_YOUR_TENANT_SPECIFIC_APPS")



    `
def public_reverse(viewname, args=None, kwargs=None, current_app=None):
    """
    public urls type public
    """
    return reverse(viewname, urlconf="configs.urls.public_urls", args=args, kwargs=kwargs, current_app=current_app)


def client_reverse(viewname, args=None, kwargs=None, current_app=None):
    """
    tenant urls type client
    """
    return reverse(viewname, urlconf="configs.urls.client_urls", args=args, kwargs=kwargs, current_app=current_app)`

**Comment by Joe3009** [comment]
The Problem is because of the url.configs in for this Multy-tenancy type. The reverse function will only lookup in public so you have to customize the reverse function, here is my example how i solve this:
(the url conf is important: urlconf="ROUTE_WHERE_YOU_DECLARE_YOUR_TENANT_SPECIFIC_APPS")


`def public_reverse(viewname, args=None, kwargs=None, current_app=None):
"""
public urls type public
"""
return reverse(viewname, urlconf="configs.urls.public_urls", args=args, kwargs=kwargs, current_app=current_app)

def client_reverse(viewname, args=None, kwargs=None, current_app=None):
"""
tenant urls type client
"""
return reverse(viewname, urlconf="configs.urls.client_urls", args=args, kwargs=kwargs, current_app=current_app)`

**Comment by Joe3009** [comment]
Its because of the reverse. This function only look up to public urls by tests. so you have to create own "reverse"-functions:


```
def public_reverse(viewname, args=None, kwargs=None, current_app=None):
    """
    public urls (Tests)
    """
    return reverse(viewname, urlconf="configs.urls.public_urls", args=args, kwargs=kwargs, current_app=current_app)


def client_reverse(viewname, args=None, kwargs=None, current_app=None):
    """
    tenant urls (test)
    """
    return reverse(viewname, urlconf="configs.urls.client_urls", args=args, kwargs=kwargs, current_app=current_app)

```

**Comment by Joe3009** [comment]
And then just use it like normal reverse for example: client_reverse("Restaurant-list")

**Comment by elinonga** [comment]
Hey @Joe3009 thank you for the feedback. 
Will try this and provide feedback. 
Can you provide me with your email if you don't mind?

**Comment by elinonga** [comment]
> Its because of the reverse. This function only look up to public urls by tests. so you have to create own "reverse"-functions:
> 
> ```
> def public_reverse(viewname, args=None, kwargs=None, current_app=None):
>     """
>     public urls (Tests)
>     """
>     return reverse(viewname, urlconf="configs.urls.public_urls", args=args, kwargs=kwargs, current_app=current_app)
> 
> 
> def client_reverse(viewname, args=None, kwargs=None, current_app=None):
>     """
>     tenant urls (test)
>     """
>     return reverse(viewname, urlconf="configs.urls.client_urls", args=args, kwargs=kwargs, current_app=current_app)
> ```

Hey @Joe3009 where should I add these? on my tests.py ? Or on a separate file (i.e; functions.py)?

**Comment by elinonga** [comment]
Thank you!

**Comment by lucasrcezimbra** [comment]
I managed to fix this by extending the `TenantClient`:

```python
from django_tenants.test.client import TenantClient
from django_tenants.utils import get_subfolder_prefix


class SubfolderTenantClient(TenantClient):
    def generic(self, method, path, *args, **kwargs):
        path = f"/{get_subfolder_prefix()}/{self.tenant.get_primary_domain().domain}{path}"
        return super().generic(method, path, *args, **kwargs)
```

Usage:

```python
# conftest.py

from django_tenants.test.cases import SubfolderTenantTestCase
from django_tenants.test.client import TenantClient
from django_tenants.utils import get_subfolder_prefix


@pytest.fixture(scope="session")
def django_db_setup(django_db_setup, django_db_blocker):
    with django_db_blocker.unblock():
        SubfolderTenantTestCase.setUpClass()

    yield

    with django_db_blocker.unblock():
        SubfolderTenantTestCase.tearDownClass()


class SubfolderTenantClient(TenantClient):
    def generic(self, method, path, *args, **kwargs):
        path = f"/{get_subfolder_prefix()}/{self.tenant.get_primary_domain().domain}{path}"
        return super().generic(method, path, *args, **kwargs)


@pytest.fixture
def client(current_user):
    return SubfolderTenantClient(SubfolderTenantTestCase.tenant)
```

**Comment by elinonga** [comment]
Hey @lucasrcezimbra  thank you for the feedback.
Will try this and provide feedback.
Can you provide me with your email if you don't mind?

**Comment by elinonga** [comment]
I managed to fix it. I used a different method from what was recommended on the thread, but still I am greatful for @Joe3009 and @lucasrcezimbra inputs.
