### ISSUE TITLE
post_migrate signals for apps not registered for tenant type causes errors

### ISSUE THREAD

**Issue by Wizely99** [django-tenants/django-tenants#979]
I am using multi-tenant types, and there is an app that is registered for tenant type 1 but not tenant type 2. This app uses the post_migrate signal to do some updates and other stuff. The problem is that when I migrate, the signal is emitted for that app even for the schema of tenant type 2, since migrations are faked into the database.

Is there a way to emit no signals when a migration is faked?Any Work around?

**Comment by kumarnmanoj** [comment]
@Wizely99 We also stuck in the same situation as you. How you handled it?

**Comment by Wizely99** [comment]
Hi @kumarnmanoj,

I ran into an issue with the [django-treenode](https://github.com/fabiocaccamo/django-treenode) package when I added it to the INSTALLED_APPS setting for some tenant types. The package uses a post-save signal that caused an exception.
See here .[<fabiocaccamo>/django-treenode#12](https://github.com/fabiocaccamo/django-treenode/issues/125)
To resolve this, I added the app to INSTALLED_APPS for all tenant types, including the public one. However, this might not be the ideal solution for your specific use case.

If you have control over the `post-save` signal  I would recommend implementing a `try-except` block to handle the exceptions.

**Comment by gone** [comment]
I fixed with this in my tenant app config:
```
def is_tenant_migration():
    """Check if current migration is in a tenant schema."""
    current_schema = connections[DEFAULT_DB_ALIAS].schema_name
    return current_schema != get_public_schema_name()


def tenant_aware_treenode_handler(sender, **kwargs):
    """
    Conditionally run treenode's post-migrate logic only for tenant schemas.

    This function wraps the original treenode signal logic.
    """
    if is_tenant_migration():
        sender_model = kwargs.get('sender')
        if hasattr(sender_model, 'update_tree'):
            sender_model.update_tree()


# Replace the original signal handler
treenode.signals.post_migrate_treenode = tenant_aware_treenode_handler
```
