### ISSUE TITLE
shell_plus

### ISSUE THREAD

**Issue by jacopsd** [django-tenants/django-tenants#985]
with django_tenants enabled, shell_plus (which is included in django-extensions) fails to load:

```
pip install django-extensions
...
python manage.py tenant_command shell_plus --schema=schema1
CommandError: Unknown command: 'shell_plus'

```

**Comment by mikicz** [comment]
Have you included django extensions in installed apps?

**Comment by jacopsd** [comment]
Indeed, that was missing
