### ISSUE TITLE
How can i access data of all tenants 

### ISSUE THREAD

**Issue by hogking** [django-tenants/django-tenants#995]
Hi everyone.

In my case, all tenant users will first log in through the same one address like 'domain.com'. After successful login, the subsequent request address is set to a specific tenant address 'tenant.domain.com'. 

The first option is to enter the account number, password and tenant name in the input box. However, due to product design reasons, I hope that ordinary users will not be aware of the existence of the tenant. 

Option two only requires an account and password. At this time, I need to use for loop of all tenants and determine which tenants contain the user (call authentication within the cycle).If there are too many tenants, there may be performance problems.

Can someone give some advices or performance optimization suggestions?

**Comment by hogking** [comment]
My login serializer code:
```
def validate(self, attrs):
# check if user exists in tenants 
for tenant in get_tenant_model().objects.all().exclude(schema_name='public'):
  self.context['request'].tenant = tenant
  user = authenticate(self.context['request'], username=attrs['username'], password=attrs['password'])
  if user is not None:
    user_tenant = tenant
    break
  if not user:
    raise ValidationError("Account Error")

# use specific tenant
with tenant_context(user_tenant):
            ...
```

**Comment by bgunebakan** [comment]
You may think using django-tenant-users for that. It create users in public schema and users can login on public schema and your code can redirect them to their tenant domain.
https://github.com/Corvia/django-tenant-users

**Comment by hogking** [comment]
Thanks for your answer @bgunebakan .
I found this project but it seems like django-tenant-users need email to be username. But in my country everyone likes to use phone number instead of email. 
I use another way to solve with this problem(use a extra table stores username and tenant_name in public schemas)
